/* The following code was generated by JFlex 1.6.1 */

/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2016 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2016 Sun Microsystems, Inc.
 */

package org.netbeans.modules.php.blade.editor.lexer;

import java.util.Objects;
import org.netbeans.spi.lexer.LexerInput;
import org.netbeans.spi.lexer.LexerRestartInfo;
import org.netbeans.modules.web.common.api.ByteStack;

@org.netbeans.api.annotations.common.SuppressWarnings({"SF_SWITCH_FALLTHROUGH", "URF_UNREAD_FIELD", "DLS_DEAD_LOCAL_STORE", "DM_DEFAULT_ENCODING", "EI_EXPOSE_REP"})

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>grammar/BladeTopColoringLexer.flex</tt>
 */
public class BladeTopColoringLexer {
/** This character denotes the end of file */
  public static final int YYEOF = LexerInput.EOF;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int ST_HTML = 2;
  public static final int ST_INLINE_PHP = 4;
  public static final int ST_BLADE_PHP = 6;
  public static final int ST_BLADE_ECHO = 8;
  public static final int ST_BLADE_ECHO_ESCAPED = 10;
  public static final int ST_DIRECTIVE = 12;
  public static final int ST_DIRECTIVE_ARGUMENTS = 14;
  public static final int ST_COMMENT = 16;
  public static final int ST_HIGHLIGHTING_ERROR = 18;
  public static final int ST_CLOSE_BLADE_PHP = 20;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9,  9, 10, 10
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\14\1\1\1\22\1\23\1\23\1\22\16\14\4\0\1\11\1\4"+
    "\2\0\1\14\3\0\1\12\4\0\1\5\2\0\12\10\2\0\1\15"+
    "\1\0\1\21\1\16\1\6\7\7\1\20\7\7\1\17\12\7\4\0"+
    "\1\10\1\0\7\7\1\20\7\7\1\17\12\7\1\2\1\0\1\3"+
    "\1\0\6\14\1\24\32\14\2\0\4\14\4\0\1\13\2\0\1\14"+
    "\7\0\1\13\4\0\1\13\5\0\27\13\1\0\37\13\1\0\u01ca\13"+
    "\4\0\14\13\16\0\5\13\7\0\1\13\1\0\1\13\21\0\160\14"+
    "\5\13\1\0\2\13\2\0\4\13\1\0\1\13\6\0\1\13\1\0"+
    "\3\13\1\0\1\13\1\0\24\13\1\0\123\13\1\0\213\13\1\0"+
    "\5\14\2\0\246\13\1\0\46\13\2\0\1\13\6\0\1\14\47\13"+
    "\1\14\6\0\1\14\1\0\55\14\1\0\1\14\1\0\2\14\1\0"+
    "\2\14\1\0\1\14\10\0\33\13\4\0\1\14\3\13\15\0\6\14"+
    "\5\0\1\14\4\0\13\14\1\0\1\14\3\0\53\13\37\14\4\0"+
    "\2\13\1\14\143\13\1\0\1\13\10\14\1\0\6\14\2\13\2\14"+
    "\1\0\4\14\2\13\12\14\3\13\2\0\1\13\17\0\1\14\1\13"+
    "\1\14\36\13\33\14\2\0\131\13\13\14\1\13\16\0\12\14\41\13"+
    "\11\14\2\13\4\0\1\13\2\0\3\14\26\13\4\14\1\13\11\14"+
    "\1\13\3\14\1\13\5\14\22\0\31\13\3\14\4\0\13\14\65\0"+
    "\23\13\2\14\1\0\22\14\13\0\61\14\66\13\3\14\1\13\22\14"+
    "\1\13\7\14\12\13\2\14\2\0\12\14\1\0\20\13\3\14\1\0"+
    "\10\13\2\0\2\13\2\0\26\13\1\0\7\13\1\0\1\13\3\0"+
    "\4\13\2\0\1\14\1\13\7\14\2\0\2\14\2\0\3\14\1\13"+
    "\10\0\1\14\4\0\2\13\1\0\3\13\2\14\2\0\12\14\2\13"+
    "\2\14\7\0\2\14\1\0\1\14\2\0\3\14\1\0\6\13\4\0"+
    "\2\13\2\0\26\13\1\0\7\13\1\0\2\13\1\0\2\13\1\0"+
    "\2\13\2\0\1\14\1\0\5\14\4\0\2\14\2\0\3\14\3\0"+
    "\1\14\7\0\4\13\1\0\1\13\7\0\14\14\3\13\1\14\13\0"+
    "\3\14\1\0\11\13\1\0\3\13\1\0\26\13\1\0\7\13\1\0"+
    "\2\13\1\0\5\13\2\0\1\14\1\13\10\14\1\0\3\14\1\0"+
    "\3\14\2\0\1\13\17\0\2\13\2\14\2\0\12\14\1\0\1\14"+
    "\7\0\7\14\1\0\3\14\1\0\10\13\2\0\2\13\2\0\26\13"+
    "\1\0\7\13\1\0\2\13\1\0\5\13\2\0\1\14\1\13\7\14"+
    "\2\0\2\14\2\0\3\14\7\0\3\14\4\0\2\13\1\0\3\13"+
    "\2\14\2\0\12\14\1\0\1\13\20\0\1\14\1\13\1\0\6\13"+
    "\3\0\3\13\1\0\4\13\3\0\2\13\1\0\1\13\1\0\2\13"+
    "\3\0\2\13\3\0\3\13\3\0\14\13\4\0\5\14\3\0\3\14"+
    "\1\0\4\14\2\0\1\13\6\0\1\14\16\0\12\14\11\0\1\14"+
    "\6\0\5\14\10\13\1\0\3\13\1\0\27\13\1\0\20\13\3\0"+
    "\1\13\7\14\1\0\3\14\1\0\4\14\7\0\2\14\1\0\2\13"+
    "\1\14\5\0\2\13\2\14\2\0\12\14\20\0\4\14\1\0\10\13"+
    "\1\0\3\13\1\0\27\13\1\0\12\13\1\0\5\13\2\0\1\14"+
    "\1\13\7\14\1\0\3\14\1\0\4\14\7\0\2\14\7\0\1\13"+
    "\1\0\2\13\2\14\2\0\12\14\1\0\2\13\15\0\5\14\10\13"+
    "\1\0\3\13\1\0\51\13\2\14\1\13\7\14\1\0\3\14\1\0"+
    "\4\14\1\13\5\0\4\14\7\0\1\14\2\13\2\14\2\0\12\14"+
    "\12\0\6\13\1\0\3\14\1\0\22\13\3\0\30\13\1\0\11\13"+
    "\1\0\1\13\2\0\7\13\3\0\1\14\4\0\6\14\1\0\1\14"+
    "\1\0\10\14\6\0\12\14\2\0\2\14\15\0\60\13\1\14\2\13"+
    "\7\14\4\0\1\14\7\13\10\14\1\0\12\14\47\0\2\13\1\0"+
    "\1\13\1\0\1\14\2\13\1\14\1\13\1\0\1\14\1\13\6\14"+
    "\4\13\1\14\7\13\1\14\3\13\1\0\1\13\1\0\1\13\2\14"+
    "\2\13\1\14\4\13\1\14\2\13\11\14\1\13\2\0\5\13\1\0"+
    "\1\13\1\0\6\14\2\0\12\14\2\0\4\13\40\0\1\13\27\0"+
    "\2\14\6\0\12\14\13\0\1\14\1\0\1\14\1\0\1\14\4\0"+
    "\2\14\10\13\1\0\44\13\4\0\24\14\1\0\2\14\5\13\13\14"+
    "\1\0\44\14\11\0\1\14\71\0\53\13\24\14\1\13\12\14\6\0"+
    "\6\13\4\14\4\13\3\14\1\13\3\14\2\13\7\14\3\13\4\14"+
    "\15\13\14\14\1\13\17\14\2\0\46\13\1\0\1\13\5\0\1\13"+
    "\2\0\53\13\1\0\u014d\13\1\0\4\13\2\0\7\13\1\0\1\13"+
    "\1\0\4\13\2\0\51\13\1\0\4\13\2\0\41\13\1\0\4\13"+
    "\2\0\7\13\1\0\1\13\1\0\4\13\2\0\17\13\1\0\71\13"+
    "\1\0\4\13\2\0\103\13\2\0\3\14\40\0\20\13\20\0\125\13"+
    "\1\14\2\0\6\14\3\0\u026c\13\2\0\21\13\1\0\32\13\5\0"+
    "\113\13\3\0\3\14\10\13\7\0\15\13\1\0\4\13\3\14\13\0"+
    "\22\13\3\14\13\0\22\13\2\14\14\0\15\13\1\0\3\13\1\0"+
    "\2\14\14\0\64\13\40\14\3\0\1\13\3\0\1\14\1\13\1\14"+
    "\2\0\12\14\41\0\4\14\1\0\12\14\6\0\130\13\1\14\7\0"+
    "\51\13\1\14\1\13\5\0\106\13\12\0\37\13\1\0\14\14\4\0"+
    "\14\14\12\0\12\14\36\13\2\0\5\13\13\0\54\13\4\0\21\14"+
    "\7\13\2\14\6\0\12\14\46\0\27\13\5\14\4\0\65\13\12\14"+
    "\1\0\35\14\2\0\13\14\6\0\12\14\15\0\1\13\10\0\16\14"+
    "\1\0\2\14\77\0\5\14\57\13\21\14\7\13\4\0\12\14\21\0"+
    "\11\14\14\0\3\14\36\13\15\14\2\13\12\14\54\13\16\14\14\0"+
    "\44\13\24\14\10\0\12\14\3\0\3\13\12\14\44\13\2\0\11\14"+
    "\7\0\53\14\2\0\3\14\20\0\3\14\1\0\25\14\4\13\1\14"+
    "\4\13\3\14\2\13\4\14\5\0\300\13\72\14\1\0\5\14\u0116\13"+
    "\2\0\6\13\2\0\46\13\2\0\6\13\2\0\10\13\1\0\1\13"+
    "\1\0\1\13\1\0\1\13\1\0\37\13\2\0\65\13\1\0\7\13"+
    "\1\0\1\13\3\0\3\13\1\0\7\13\3\0\4\13\2\0\6\13"+
    "\4\0\15\13\5\0\3\13\1\0\7\13\16\0\5\14\30\0\1\23"+
    "\1\23\5\14\20\0\2\14\23\0\1\14\13\0\5\14\1\0\12\14"+
    "\1\0\1\13\15\0\1\13\20\0\15\13\3\0\40\14\20\0\15\14"+
    "\4\0\1\14\3\0\14\14\21\0\1\13\4\0\1\13\2\0\12\13"+
    "\1\0\1\13\3\0\5\13\6\0\1\13\1\0\1\13\1\0\1\13"+
    "\1\0\4\13\1\0\13\13\2\0\4\13\5\0\5\13\4\0\1\13"+
    "\21\0\43\14\2\13\4\14\u0a77\0\57\13\1\0\57\13\1\0\205\13"+
    "\6\0\4\13\3\14\2\13\14\0\46\13\1\0\1\13\5\0\1\13"+
    "\2\0\70\13\7\0\1\13\17\0\1\14\27\13\11\0\7\13\1\0"+
    "\7\13\1\0\7\13\1\0\7\13\1\0\7\13\1\0\7\13\1\0"+
    "\7\13\1\0\7\13\1\0\40\14\57\0\1\13\u01d5\0\2\13\1\14"+
    "\31\0\17\14\1\0\5\13\2\0\3\14\2\13\4\0\126\13\2\0"+
    "\2\14\2\0\3\13\1\0\132\13\1\0\4\13\5\0\51\13\2\14"+
    "\1\0\136\13\21\0\33\13\5\14\60\0\20\13\u0200\0\u19b6\13\12\14"+
    "\100\0\u51cd\13\60\14\3\0\u048d\13\103\0\56\13\2\0\u010d\13\3\0"+
    "\20\13\12\14\2\13\24\0\57\13\1\14\4\0\12\14\1\0\37\13"+
    "\2\14\106\13\14\14\45\0\11\13\2\0\147\13\2\0\4\13\1\14"+
    "\36\13\2\14\2\13\16\14\2\0\11\14\52\0\2\14\13\13\1\14"+
    "\3\13\1\14\4\13\1\14\27\13\5\14\4\0\1\14\13\0\1\14"+
    "\7\0\64\13\14\0\2\14\62\13\22\14\12\0\12\14\6\0\22\14"+
    "\6\13\3\0\1\13\1\0\15\14\34\13\10\14\2\0\27\13\15\14"+
    "\14\0\35\13\3\0\4\14\57\13\16\14\16\0\1\13\12\14\6\0"+
    "\5\13\1\14\12\13\12\14\5\13\1\0\51\13\16\14\11\0\3\13"+
    "\1\14\10\13\2\14\2\0\12\14\6\0\27\13\3\0\1\13\3\14"+
    "\62\13\1\14\1\13\3\14\2\13\2\14\5\13\2\14\1\13\1\14"+
    "\1\13\30\0\3\13\2\0\13\13\5\14\2\0\3\13\2\14\12\0"+
    "\6\13\2\0\6\13\2\0\6\13\11\0\7\13\1\0\7\13\1\0"+
    "\53\13\1\0\4\13\4\14\2\13\4\14\6\0\120\14\43\13\10\14"+
    "\1\0\2\14\2\0\12\14\6\0\u2ba4\13\14\0\27\13\4\0\61\13"+
    "\u2104\0\u016e\13\2\0\152\13\46\0\7\13\14\0\5\13\5\0\1\13"+
    "\1\14\12\13\1\0\15\13\1\0\5\13\1\0\1\13\1\0\2\13"+
    "\1\0\2\13\1\0\154\13\41\0\u016b\13\22\0\100\13\2\0\66\13"+
    "\50\0\14\13\1\14\3\0\20\14\20\0\20\14\3\0\2\14\30\0"+
    "\3\14\31\0\1\14\6\0\5\13\1\0\207\13\2\0\1\14\4\0"+
    "\1\14\13\0\12\14\7\0\32\13\4\0\1\14\1\0\32\13\13\0"+
    "\131\13\3\0\6\13\2\0\6\13\2\0\6\13\2\0\3\13\3\0"+
    "\2\14\3\0\2\14\22\0\3\14\4\0\14\13\1\0\32\13\1\0"+
    "\23\13\1\0\2\13\1\0\17\13\2\0\16\13\42\0\173\13\105\0"+
    "\65\14\210\0\1\14\202\0\35\13\3\0\61\13\17\0\1\14\37\0"+
    "\40\13\15\0\3\14\21\13\1\14\10\13\1\14\5\0\46\13\5\14"+
    "\5\0\36\13\2\0\44\13\4\0\10\13\1\0\5\14\52\0\236\13"+
    "\2\0\12\14\6\0\44\14\4\0\44\14\4\0\50\13\10\0\64\13"+
    "\234\0\u0137\13\11\0\26\13\12\0\10\13\230\0\6\13\2\0\1\13"+
    "\1\0\54\13\1\0\2\13\3\0\1\13\2\0\27\13\12\0\27\13"+
    "\11\0\37\13\101\0\23\14\1\0\2\14\12\0\26\13\12\0\32\13"+
    "\106\0\70\13\6\0\2\13\100\0\1\13\3\14\1\0\2\14\5\0"+
    "\4\14\4\13\1\0\3\13\1\0\33\13\2\14\2\0\3\14\4\0"+
    "\1\14\40\0\35\13\3\0\35\13\43\0\10\13\1\0\34\13\2\14"+
    "\31\0\66\13\12\0\26\13\12\0\23\13\15\0\22\13\156\0\111\13"+
    "\67\0\63\14\15\0\63\14\15\0\50\14\10\0\12\14\u0146\0\52\14"+
    "\1\0\2\14\3\0\2\14\116\0\35\14\12\0\1\14\10\0\41\14"+
    "\137\0\25\14\33\0\27\14\11\0\3\14\65\13\17\14\37\0\12\14"+
    "\17\0\4\14\55\13\13\14\2\0\1\14\17\0\1\14\2\0\31\13"+
    "\7\0\12\14\6\0\3\14\44\13\16\14\1\0\12\14\4\0\4\14"+
    "\10\0\43\13\1\14\2\0\1\13\11\0\3\14\60\13\16\14\4\13"+
    "\4\0\4\14\1\0\14\14\1\13\1\0\1\14\43\0\22\13\1\0"+
    "\31\13\14\14\6\0\1\14\101\0\7\14\1\0\1\14\1\0\4\14"+
    "\1\0\17\14\1\0\12\14\7\0\57\13\14\14\5\0\12\14\6\0"+
    "\4\14\1\0\10\13\2\0\2\13\2\0\26\13\1\0\7\13\1\0"+
    "\2\13\1\0\5\13\1\0\2\14\1\13\7\14\2\0\2\14\2\0"+
    "\3\14\2\0\1\14\6\0\1\14\5\0\5\13\2\14\2\0\7\14"+
    "\3\0\5\14\213\0\113\14\5\0\12\14\4\0\4\14\36\0\60\13"+
    "\24\14\2\13\1\0\1\13\10\0\12\14\246\0\57\13\7\14\2\0"+
    "\11\14\27\0\6\14\42\0\60\13\21\14\3\0\1\13\13\0\12\14"+
    "\46\0\53\13\16\14\7\0\12\14\66\0\33\14\2\0\17\14\4\0"+
    "\12\14\306\0\73\14\145\0\100\13\12\14\25\0\1\13\7\14\2\0"+
    "\1\14\2\0\10\14\1\0\2\14\1\0\36\14\1\0\2\14\2\0"+
    "\11\14\14\0\12\14\106\0\10\14\2\0\56\14\2\0\10\14\1\0"+
    "\2\14\33\0\77\14\10\0\1\14\10\0\112\14\3\0\1\14\42\0"+
    "\71\13\u0107\0\11\14\1\0\55\14\1\0\11\14\17\0\12\14\30\0"+
    "\36\14\2\0\26\14\1\0\16\14\111\0\7\14\1\0\2\14\1\0"+
    "\54\14\3\0\1\14\1\0\2\14\1\0\11\14\10\0\12\14\6\0"+
    "\6\14\1\0\2\14\1\0\45\14\1\0\2\14\1\0\6\14\7\0"+
    "\12\14\u0136\0\27\14\271\0\1\14\54\0\4\14\37\0\u0399\13\1\14"+
    "\146\0\157\14\21\0\304\14\u0abc\0\u042f\13\1\0\11\14\u0fc7\0\u0247\14"+
    "\u21b9\0\u0239\13\7\0\37\13\1\0\12\14\146\0\36\13\2\0\5\14"+
    "\13\0\60\13\7\14\11\0\4\13\14\0\12\14\11\0\25\13\5\0"+
    "\23\13\u02b0\0\100\14\200\0\105\13\6\14\4\0\1\14\1\13\67\14"+
    "\7\0\4\14\15\13\100\0\2\14\1\0\2\14\13\0\2\14\16\0"+
    "\u17f8\14\10\0\u04d6\14\52\0\11\14\u22f7\0\2\13\u011d\14\61\0\3\14"+
    "\21\0\4\14\10\0\u018c\14\u0904\0\153\13\5\0\15\13\3\0\11\13"+
    "\7\0\12\13\3\0\2\14\1\0\4\14\u14c1\0\5\14\3\0\26\14"+
    "\2\0\7\14\36\0\4\14\224\0\3\14\u01bb\0\125\13\1\0\107\13"+
    "\1\0\2\13\2\0\1\13\2\0\2\13\2\0\4\13\1\0\14\13"+
    "\1\0\1\13\1\0\7\13\1\0\101\13\1\0\4\13\2\0\10\13"+
    "\1\0\7\13\1\0\34\13\1\0\4\13\1\0\5\13\1\0\1\13"+
    "\3\0\7\13\1\0\u0154\13\2\0\31\13\1\0\31\13\1\0\37\13"+
    "\1\0\31\13\1\0\37\13\1\0\31\13\1\0\37\13\1\0\31\13"+
    "\1\0\37\13\1\0\31\13\1\0\10\13\2\0\62\14\u0200\0\67\14"+
    "\4\0\62\14\10\0\1\14\16\0\1\14\26\0\5\14\1\0\17\14"+
    "\u0550\0\7\14\1\0\21\14\2\0\7\14\1\0\2\14\1\0\5\14"+
    "\325\0\55\14\3\0\16\14\2\0\12\14\4\0\1\14\u0171\0\72\14"+
    "\5\0\1\14\u0500\0\305\13\13\0\7\14\51\0\114\14\4\0\12\14"+
    "\u0356\0\1\14\u014f\0\4\13\1\0\33\13\1\0\2\13\1\0\1\13"+
    "\2\0\1\13\1\0\12\13\1\0\4\13\1\0\1\13\1\0\1\13"+
    "\6\0\1\13\4\0\1\13\1\0\1\13\1\0\1\13\1\0\3\13"+
    "\1\0\2\13\1\0\1\13\2\0\1\13\1\0\1\13\1\0\1\13"+
    "\1\0\1\13\1\0\1\13\1\0\2\13\1\0\1\13\2\0\4\13"+
    "\1\0\7\13\1\0\4\13\1\0\4\13\1\0\1\13\1\0\12\13"+
    "\1\0\21\13\5\0\3\13\1\0\5\13\1\0\21\13\u0d34\0\12\14"+
    "\u0406\0\ua6d7\13\7\14\42\0\u1035\13\13\0\336\13\2\0\u1682\14\16\0"+
    "\u1d31\14\u0c1f\0\u021e\13\u05e2\0\u134b\14\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uecc0\0"+
    "\1\14\36\0\140\14\200\0\360\14\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\13\0\1\1\1\2\1\1\1\3\1\1\2\4\1\5"+
    "\3\1\2\6\1\7\1\1\1\10\1\11\1\12\2\0"+
    "\1\13\1\0\1\14\1\0\2\15\1\0\1\16\2\0"+
    "\1\17\1\0\1\20\2\0\1\21\1\22\1\23";

  private static int [] zzUnpackAction() {
    int [] result = new int[49];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\25\0\52\0\77\0\124\0\151\0\176\0\223"+
    "\0\250\0\275\0\322\0\322\0\347\0\374\0\322\0\u0111"+
    "\0\322\0\u0126\0\322\0\u013b\0\u0150\0\u0165\0\322\0\u017a"+
    "\0\322\0\u018f\0\322\0\u01a4\0\322\0\u01b9\0\u01ce\0\322"+
    "\0\u01e3\0\322\0\u01f8\0\u020d\0\u0222\0\u0237\0\322\0\u024c"+
    "\0\u0261\0\322\0\u0276\0\322\0\u028b\0\u02a0\0\322\0\322"+
    "\0\322";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[49];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\14\1\15\1\16\3\14\1\17\2\14\1\15\3\14"+
    "\1\20\4\14\1\15\2\0\2\14\1\16\3\14\1\17"+
    "\6\14\1\20\4\14\3\0\16\21\1\22\6\21\25\23"+
    "\1\14\1\15\1\24\1\25\5\14\1\15\10\14\1\15"+
    "\2\0\1\14\1\15\2\14\1\26\4\14\1\15\10\14"+
    "\1\15\2\0\1\27\1\15\4\27\1\30\2\27\1\15"+
    "\10\27\1\15\2\27\25\31\1\14\1\15\3\14\1\32"+
    "\3\14\1\15\10\14\1\15\2\0\1\33\1\34\7\33"+
    "\1\34\10\33\1\34\30\0\1\15\7\0\1\15\10\0"+
    "\1\15\4\0\1\35\1\0\1\36\36\0\1\37\27\0"+
    "\1\40\5\0\1\41\25\0\1\42\25\0\1\43\27\0"+
    "\1\44\3\0\1\45\3\0\2\44\11\0\1\46\20\0"+
    "\1\34\7\0\1\34\10\0\1\34\6\0\1\47\37\0"+
    "\1\50\12\0\1\51\22\0\1\52\30\0\2\44\1\53"+
    "\1\54\2\45\2\0\2\44\3\0\1\45\7\0\2\45"+
    "\2\0\2\45\2\0\2\45\3\0\1\45\3\0\1\55"+
    "\41\0\1\56\11\0\1\57\30\0\1\53\1\54\15\0"+
    "\1\60\40\0\1\61\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[693];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\12\0\1\10\1\11\2\1\1\11\1\1\1\11\1\1"+
    "\1\11\3\1\1\11\1\1\1\11\1\1\1\11\1\1"+
    "\1\11\2\0\1\11\1\0\1\11\1\0\2\1\1\0"+
    "\1\11\2\0\1\11\1\0\1\11\2\0\3\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[49];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the
   * matched text
   */
  private int yycolumn;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF = false;

  /* user code: */
    private ByteStack stack = new ByteStack();
    private LexerInput input;
    private int parenBalanceInDirective = 0; //for directive arguments

    public BladeTopColoringLexer(LexerRestartInfo<?> info) {
        this.input = info.input();
        if(info.state() != null) {
            //reset state
            setState((LexerState) info.state(), parenBalanceInDirective);
        } else {
            //initial state
            stack.push(YYINITIAL);
            zzState = YYINITIAL;
            zzLexicalState = YYINITIAL;
        }

    }

    public static final class LexerState  {
        final ByteStack stack;
        /** the current state of the DFA */
        final int zzState;
        /** the current lexical state */
        final int zzLexicalState;
        final int parenBalanceInDirective; 

        LexerState(ByteStack stack, int zzState, int zzLexicalState, int parenBalanceInDirective) {
            this.stack = stack;
            this.zzState = zzState;
            this.zzLexicalState = zzLexicalState;
            this.parenBalanceInDirective = parenBalanceInDirective;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (obj == null || obj.getClass() != this.getClass()) {
                return false;
            }
            LexerState state = (LexerState) obj;
            return (this.stack.equals(state.stack)
                && (this.zzState == state.zzState)
                //&& (this.zzLexicalState == state.zzLexicalState)
                //&& (this.parenBalanceInDirective == state.parenBalanceInDirective)
                );
        }

        @Override
        public int hashCode() {
            int hash = 11;
            hash = 31 * hash + this.zzState;
            hash = 31 * hash + this.zzLexicalState;
            hash = 31 * hash + this.parenBalanceInDirective;
            if (stack != null) {
                hash = 31 * hash + this.stack.hashCode();
            }
            return hash;
        }
    }

    public LexerState getState() {
        return new LexerState(stack.copyOf(), zzState, zzLexicalState, parenBalanceInDirective);
    }

    public void setState(LexerState state, int parenBalanceInDirective) {
        this.stack.copyFrom(state.stack);
        this.zzState = state.zzState;
        this.zzLexicalState = state.zzLexicalState;
        this.parenBalanceInDirective = state.parenBalanceInDirective;
    }

//getParameters??

    protected int getZZLexicalState() {
        return zzLexicalState;
    }

    //other functions

    protected void pushBack(int i) {
        yypushback(i);
    }

    protected void popState() {
        yybegin(stack.pop());
    }

    protected void pushState(final int state) {
        stack.push(getZZLexicalState());
        yybegin(state);
    }

    /**
     * Returns the smallest of multiple index values.
     *
     * @param values values
     * @return the smallest of multiple index values, -1 if all values are -1
     */
    private static int minIndex(int... values) {
        assert values.length != 0 : "No values"; // NOI18N
        boolean first = true;
        int min = -1;
        for (int value : values) {
            if (value == -1) {
                continue;
            }
            if (first) {
                first = false;
                min = value;
                continue;
            }
            min = Math.min(min, value);
        }
        return min;
    }

    /**
     * Get the first whitespace index of text.
     *
     * @param text the text
     * @return the first index of whitespace if whitespace exists, otherwise -1
     */
    private static int firstWhitespaceIndexOf(String text) {
        return minIndex(
            text.indexOf(' '),
            text.indexOf('\n'),
            text.indexOf('\r'),
            text.indexOf('\t')
        );
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public BladeTopColoringLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 3648) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }



  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return input.readText().toString();
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
     return input.readText().charAt(pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return input.readLength();
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    input.backup(number);
    //zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public BladeTopTokenId findNextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    //int zzCurrentPosL;
    //int zzMarkedPosL;
    //int zzEndReadL = zzEndRead;
    //char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      //zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      //zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
      int tokenLength = 0;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
            zzInput = input.read();

            if(zzInput == LexerInput.EOF) {
                //end of input reached
                zzInput = YYEOF;
                break zzForAction;
                //notice: currently LexerInput.EOF == YYEOF
            }

          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            tokenLength = input.readLength();
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      if(zzInput != YYEOF) {
         input.backup(input.readLength() - tokenLength);
      }

        //action
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { //if (yylength() > 1) {
        //    yypushback(1);
        //}
        //pushState(ST_HIGHLIGHTING_ERROR);
            }
          case 20: break;
          case 2: 
            { 
            }
          case 21: break;
          case 3: 
            { pushState(ST_DIRECTIVE);
    	if (yylength() > 1){
    		yypushback(1);
    		return BladeTopTokenId.T_HTML;
    	}
            }
          case 22: break;
          case 4: 
            { //close inline php anychar
		String yytext = yytext();
		if (yytext.endsWith("?>")){
			//using any char
			popState();
			return BladeTopTokenId.T_PHP;
        }
            }
          case 23: break;
          case 5: 
            { String yytext = yytext();
		if (yytext.endsWith("@endphp")){
	        stack.clear();
			pushState(YYINITIAL);
	        return BladeTopTokenId.T_DIRECTIVE;
        }
            }
          case 24: break;
          case 6: 
            { //any char directive
		String yytext = yytext();
		if (yytext.endsWith("(")){
			parenBalanceInDirective++;
	        pushState(ST_DIRECTIVE_ARGUMENTS);
	        break;
		}
                if (yytext.endsWith("\"")){
			stack.clear();
			pushState(YYINITIAL);
			if (yylength() > 1){
	            yypushback(1);
	        }
	        return BladeTopTokenId.T_DIRECTIVE;
		}
            }
          case 25: break;
          case 7: 
            { String yytext = yytext();
		if (yytext.endsWith("(")){
			parenBalanceInDirective++;
		}
		if (yytext.endsWith(")")){
			parenBalanceInDirective--;
			if (parenBalanceInDirective == 0){
				stack.clear();
				pushState(YYINITIAL);
				return BladeTopTokenId.T_DIRECTIVE;
			}
		}
            }
          case 26: break;
          case 8: 
            { return BladeTopTokenId.T_HTML;
            }
          case 27: break;
          case 9: 
            { popState();
        return BladeTopTokenId.T_HTML;
            }
          case 28: break;
          case 10: 
            { //open echo
                String yytext = yytext();
                pushState(ST_BLADE_ECHO);
                if (yylength() > 2){
                    yypushback(2);
                    return BladeTopTokenId.T_HTML;
                }
            }
          case 29: break;
          case 11: 
            { //close inline php
		popState();
		return BladeTopTokenId.T_PHP;
            }
          case 30: break;
          case 12: 
            { //close echo
                String yytext = yytext();
                stack.clear();
                pushState(YYINITIAL);
                if (yytext.startsWith("{{--")){
                    return BladeTopTokenId.T_BLADE_COMMENT;
                }
                return BladeTopTokenId.T_BLADE;
            }
          case 31: break;
          case 13: 
            { //simple directive
        String yytext = yytext();
        if (yytext.equals("@php")){
            pushState(ST_BLADE_PHP);
            break;
        }
        stack.clear();
        pushState(YYINITIAL);
        return BladeTopTokenId.T_DIRECTIVE;
            }
          case 32: break;
          case 14: 
            { //open echo escaoed
        pushState(ST_BLADE_ECHO_ESCAPED);
        if (yylength() > 3){
            yypushback(3);
            return BladeTopTokenId.T_HTML;
        }
            }
          case 33: break;
          case 15: 
            { //close echo escaped
        popState();
        return BladeTopTokenId.T_BLADE;
            }
          case 34: break;
          case 16: 
            { //directive function
        String yytext = yytext();
        parenBalanceInDirective++;
        pushState(ST_DIRECTIVE_ARGUMENTS);
        break;
            }
          case 35: break;
          case 17: 
            { pushState(ST_COMMENT);
        if (yylength() > 4){
            yypushback(4);
            return BladeTopTokenId.T_HTML;
        }
            }
          case 36: break;
          case 18: 
            { //do twice
        popState();
        popState();
        return BladeTopTokenId.T_BLADE_COMMENT;
            }
          case 37: break;
          case 19: 
            { //inline php
        pushState(ST_INLINE_PHP);
        if (yylength() > 5){
            yypushback(5);
            return BladeTopTokenId.T_HTML;
        }
            }
          case 38: break;
      //end of value
      default:
         if (zzInput == YYEOF){
            if(input.readLength() > 0) {
                // backup eof
                String yytext = yytext();
                input.backup(1);
                //and return the text as error token
                if (getState().equals(ST_DIRECTIVE)){
                    return BladeTopTokenId.T_DIRECTIVE;
                }
                
                return BladeTopTokenId.T_HTML;
                } else {
                    String yytext = yytext();
                    return null;
                }
        } else {
            zzScanError(ZZ_NO_MATCH);
          //no match
        }
      }
    }
  }


}
