/* The following code was generated by JFlex 1.4.3 on 3/3/23 8:12 PM */

   /*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2016 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2016 Sun Microsystems, Inc.
 */

package org.netbeans.modules.php.blade.editor.lexer;

import org.netbeans.api.lexer.TokenId;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.netbeans.spi.lexer.LexerInput;
import org.netbeans.spi.lexer.LexerRestartInfo;
import org.netbeans.modules.php.blade.editor.common.ByteStack;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/3/23 8:12 PM from the specification file
 * <tt>C:/LOCAL_P5_APPS/lmc/blade-php/tools/BladeColoringLexer.flex</tt>
 */
public class BladeColoringLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = LexerInput.EOF;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int ST_BLADE_PARAMETER_EXPRESSION = 26;
  public static final int ST_LOOKING_FOR_PARAMETER_EXPRESSION = 24;
  public static final int ST_AFTER_DIRECTIVE_ARG = 30;
  public static final int ST_PHP = 4;
  public static final int ST_COMMENT = 20;
  public static final int ST_BLADE_ARGUMENT = 28;
  public static final int ST_BLADE_PHP = 10;
  public static final int ST_BLADE_ECHO = 12;
  public static final int ST_DIRECTIVE = 18;
  public static final int ST_BLADE_ECHO_ESCAPED = 16;
  public static final int YYINITIAL = 0;
  public static final int ST_VALIDATE_BLADE_ECHO = 14;
  public static final int ST_INLINE_PHP = 8;
  public static final int ST_PHP_ECHO = 6;
  public static final int ST_HTML = 2;
  public static final int ST_CLOSE_BLADE_PHP = 22;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  0,  0,  4,  4,  5,  5,  0,  0, 
     6,  6,  0,  0,  7,  7,  0,  0,  8,  8,  9,  9,  0,  0,  0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\2\0\1\2\22\0\1\1\1\6\1\46\2\0"+
    "\1\54\2\0\1\44\1\45\2\53\1\0\1\7\1\13\1\52\12\11"+
    "\1\47\1\0\1\14\1\21\1\20\1\15\1\12\1\34\1\50\1\31"+
    "\1\24\1\22\1\43\1\36\1\17\1\26\1\10\1\51\1\27\1\35"+
    "\1\23\1\33\1\16\1\10\1\37\1\30\1\32\1\41\1\10\1\40"+
    "\1\42\1\25\1\10\4\0\1\10\1\0\1\34\1\50\1\31\1\24"+
    "\1\22\1\43\1\36\1\17\1\26\1\10\1\51\1\27\1\35\1\23"+
    "\1\33\1\16\1\10\1\37\1\30\1\32\1\41\1\10\1\40\1\42"+
    "\1\25\1\10\1\4\1\55\1\5\1\0\53\10\1\10\12\10\1\10"+
    "\4\10\1\10\5\10\27\10\1\10\37\10\1\10\10\10\u01c2\10\4\0"+
    "\14\10\16\0\5\10\7\0\1\10\1\0\1\10\201\0\5\10\1\0"+
    "\2\10\2\0\4\10\10\0\1\10\1\0\3\10\1\0\1\10\1\0"+
    "\24\10\1\0\123\10\1\0\213\10\10\0\236\10\11\0\46\10\2\0"+
    "\1\10\7\0\47\10\110\0\33\10\5\0\3\10\55\0\53\10\25\0"+
    "\12\11\4\0\2\10\1\0\143\10\1\0\1\10\17\0\2\10\7\0"+
    "\2\10\12\11\3\10\2\0\1\10\20\0\1\10\1\0\36\10\35\0"+
    "\131\10\13\0\1\10\16\0\12\11\41\10\11\0\2\10\4\0\1\10"+
    "\5\0\26\10\4\0\1\10\11\0\1\10\3\0\1\10\27\0\31\10"+
    "\107\0\1\10\1\0\13\10\127\0\66\10\3\0\1\10\22\0\1\10"+
    "\7\0\12\10\4\0\12\11\1\0\7\10\1\0\7\10\5\0\10\10"+
    "\2\0\2\10\2\0\26\10\1\0\7\10\1\0\1\10\3\0\4\10"+
    "\3\0\1\10\20\0\1\10\15\0\2\10\1\0\3\10\4\0\12\11"+
    "\2\10\23\0\6\10\4\0\2\10\2\0\26\10\1\0\7\10\1\0"+
    "\2\10\1\0\2\10\1\0\2\10\37\0\4\10\1\0\1\10\7\0"+
    "\12\11\2\0\3\10\20\0\11\10\1\0\3\10\1\0\26\10\1\0"+
    "\7\10\1\0\2\10\1\0\5\10\3\0\1\10\22\0\1\10\17\0"+
    "\2\10\4\0\12\11\25\0\10\10\2\0\2\10\2\0\26\10\1\0"+
    "\7\10\1\0\2\10\1\0\5\10\3\0\1\10\36\0\2\10\1\0"+
    "\3\10\4\0\12\11\1\0\1\10\21\0\1\10\1\0\6\10\3\0"+
    "\3\10\1\0\4\10\3\0\2\10\1\0\1\10\1\0\2\10\3\0"+
    "\2\10\3\0\3\10\3\0\14\10\26\0\1\10\25\0\12\11\25\0"+
    "\10\10\1\0\3\10\1\0\27\10\1\0\12\10\1\0\5\10\3\0"+
    "\1\10\32\0\2\10\6\0\2\10\4\0\12\11\25\0\10\10\1\0"+
    "\3\10\1\0\27\10\1\0\12\10\1\0\5\10\3\0\1\10\40\0"+
    "\1\10\1\0\2\10\4\0\12\11\1\0\2\10\22\0\10\10\1\0"+
    "\3\10\1\0\51\10\2\0\1\10\20\0\1\10\21\0\2\10\4\0"+
    "\12\11\12\0\6\10\5\0\22\10\3\0\30\10\1\0\11\10\1\0"+
    "\1\10\2\0\7\10\72\0\60\10\1\0\2\10\14\0\7\10\11\0"+
    "\12\11\47\0\2\10\1\0\1\10\2\0\2\10\1\0\1\10\2\0"+
    "\1\10\6\0\4\10\1\0\7\10\1\0\3\10\1\0\1\10\1\0"+
    "\1\10\2\0\2\10\1\0\4\10\1\0\2\10\11\0\1\10\2\0"+
    "\5\10\1\0\1\10\11\0\12\11\2\0\4\10\40\0\1\10\37\0"+
    "\12\11\26\0\10\10\1\0\44\10\33\0\5\10\163\0\53\10\24\0"+
    "\1\10\12\11\6\0\6\10\4\0\4\10\3\0\1\10\3\0\2\10"+
    "\7\0\3\10\4\0\15\10\14\0\1\10\1\0\12\11\6\0\46\10"+
    "\1\0\1\10\5\0\1\10\2\0\53\10\1\0\u014d\10\1\0\4\10"+
    "\2\0\7\10\1\0\1\10\1\0\4\10\2\0\51\10\1\0\4\10"+
    "\2\0\41\10\1\0\4\10\2\0\7\10\1\0\1\10\1\0\4\10"+
    "\2\0\17\10\1\0\71\10\1\0\4\10\2\0\103\10\45\0\20\10"+
    "\20\0\125\10\14\0\u026c\10\2\0\21\10\1\0\32\10\5\0\113\10"+
    "\25\0\15\10\1\0\4\10\16\0\22\10\16\0\22\10\16\0\15\10"+
    "\1\0\3\10\17\0\64\10\43\0\1\10\4\0\1\10\3\0\12\11"+
    "\46\0\12\11\6\0\130\10\10\0\51\10\1\0\1\10\5\0\106\10"+
    "\12\0\35\10\51\0\12\11\36\10\2\0\5\10\13\0\54\10\25\0"+
    "\7\10\10\0\12\11\46\0\27\10\11\0\65\10\53\0\12\11\6\0"+
    "\12\11\15\0\1\10\135\0\57\10\21\0\7\10\4\0\12\11\51\0"+
    "\36\10\15\0\2\10\12\11\54\10\32\0\44\10\34\0\12\11\3\0"+
    "\3\10\12\11\44\10\153\0\4\10\1\0\4\10\3\0\2\10\11\0"+
    "\300\10\100\0\u0116\10\2\0\6\10\2\0\46\10\2\0\6\10\2\0"+
    "\10\10\1\0\1\10\1\0\1\10\1\0\1\10\1\0\37\10\2\0"+
    "\65\10\1\0\7\10\1\0\1\10\3\0\3\10\1\0\7\10\3\0"+
    "\4\10\2\0\6\10\4\0\15\10\5\0\3\10\1\0\7\10\164\0"+
    "\1\10\15\0\1\10\20\0\15\10\145\0\1\10\4\0\1\10\2\0"+
    "\12\10\1\0\1\10\3\0\5\10\6\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\0\4\10\1\0\13\10\2\0\4\10\5\0\5\10\4\0"+
    "\1\10\64\0\2\10\u0a7b\0\57\10\1\0\57\10\1\0\205\10\6\0"+
    "\4\10\3\0\2\10\14\0\46\10\1\0\1\10\5\0\1\10\2\0"+
    "\70\10\7\0\1\10\20\0\27\10\11\0\7\10\1\0\7\10\1\0"+
    "\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0"+
    "\7\10\120\0\1\10\u01d5\0\2\10\52\0\5\10\5\0\2\10\4\0"+
    "\126\10\6\0\3\10\1\0\132\10\1\0\4\10\5\0\51\10\3\0"+
    "\136\10\21\0\33\10\65\0\20\10\u0200\0\u19b6\10\112\0\u51cd\10\63\0"+
    "\u048d\10\103\0\56\10\2\0\u010d\10\3\0\20\10\12\11\2\10\24\0"+
    "\57\10\20\0\31\10\10\0\106\10\61\0\11\10\2\0\147\10\2\0"+
    "\4\10\1\0\4\10\14\0\13\10\115\0\12\10\1\0\3\10\1\0"+
    "\4\10\1\0\27\10\35\0\64\10\16\0\62\10\34\0\12\11\30\0"+
    "\6\10\3\0\1\10\4\0\12\11\34\10\12\0\27\10\31\0\35\10"+
    "\7\0\57\10\34\0\1\10\12\11\46\0\51\10\27\0\3\10\1\0"+
    "\10\10\4\0\12\11\6\0\27\10\3\0\1\10\5\0\60\10\1\0"+
    "\1\10\3\0\2\10\2\0\5\10\2\0\1\10\1\0\1\10\30\0"+
    "\3\10\2\0\13\10\7\0\3\10\14\0\6\10\2\0\6\10\2\0"+
    "\6\10\11\0\7\10\1\0\7\10\221\0\43\10\15\0\12\11\6\0"+
    "\u2ba4\10\14\0\27\10\4\0\61\10\u2104\0\u016e\10\2\0\152\10\46\0"+
    "\7\10\14\0\5\10\5\0\1\10\1\0\12\10\1\0\15\10\1\0"+
    "\5\10\1\0\1\10\1\0\2\10\1\0\2\10\1\0\154\10\41\0"+
    "\u016b\10\22\0\100\10\2\0\66\10\50\0\14\10\164\0\5\10\1\0"+
    "\207\10\23\0\12\11\7\0\32\10\6\0\32\10\13\0\131\10\3\0"+
    "\6\10\2\0\6\10\2\0\6\10\2\0\3\10\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\12\0\1\1\1\2\2\3\5\1\1\4\1\0\1\4"+
    "\2\0\1\4\1\0\2\4\1\5\2\6\2\4\1\5"+
    "\2\6\1\4\2\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\13\1\0\1\17\3\0\1\20"+
    "\1\21\1\22\14\20\2\0\1\23\1\0\1\24\4\0"+
    "\1\25\5\0\1\26\2\0\1\27\1\30\1\31\1\0"+
    "\11\20\1\32\11\20\1\0\1\33\1\0\1\34\1\0"+
    "\2\35\1\0\1\36\2\0\1\37\1\40\1\0\1\41"+
    "\17\20\1\42\1\20\3\0\1\43\1\0\1\44\1\0"+
    "\6\20\1\45\1\46\4\20\1\47\1\20\1\50\5\20"+
    "\1\51\2\0\1\52\1\0\3\20\1\53\4\20\1\54"+
    "\1\20\1\55\4\20\3\0\1\56\1\20\1\57\1\20"+
    "\1\60\1\61\6\20\1\62\1\63\1\0\3\20\1\64"+
    "\1\65\1\66\1\20\1\67\1\20\1\0\5\20\1\0"+
    "\4\20\1\0\1\70\1\71\1\72\1\20\1\0\1\20"+
    "\1\0\1\20\1\0\1\20\1\0\1\73\2\0\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[242];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\u0114\0\u0142"+
    "\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284\0\0"+
    "\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u033c\0\u036a\0\u0398\0\u03c6"+
    "\0\u03f4\0\u03f4\0\u0422\0\u0450\0\u047e\0\u04ac\0\u0450\0\u04da"+
    "\0\u0508\0\u0536\0\u0564\0\u0508\0\u0592\0\u05c0\0\u05ee\0\0"+
    "\0\u061c\0\u064a\0\0\0\u0678\0\u06a6\0\u0678\0\0\0\0"+
    "\0\u06d4\0\u0702\0\u0730\0\u075e\0\u078c\0\u07ba\0\0\0\0"+
    "\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce\0\u08fc\0\u092a"+
    "\0\u0958\0\u0986\0\u09b4\0\u09e2\0\u0a10\0\u036a\0\0\0\u0a3e"+
    "\0\0\0\u0422\0\u0a6c\0\u0450\0\u0a9a\0\u0ac8\0\u0508\0\u0af6"+
    "\0\u0b24\0\u0b52\0\u0b80\0\0\0\u0678\0\u0bae\0\u0bdc\0\0"+
    "\0\0\0\u0c0a\0\u0c38\0\u0c66\0\u0c94\0\u0cc2\0\u0cf0\0\u0d1e"+
    "\0\u0d4c\0\u0d7a\0\u0da8\0\u07ba\0\u0dd6\0\u0e04\0\u0e32\0\u0e60"+
    "\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18\0\u0f46\0\u0f74\0\0\0\u0fa2"+
    "\0\0\0\u0fd0\0\u0ac8\0\0\0\u0ffe\0\0\0\u102c\0\u105a"+
    "\0\0\0\0\0\u1088\0\u07ba\0\u10b6\0\u10e4\0\u1112\0\u1140"+
    "\0\u116e\0\u119c\0\u11ca\0\u11f8\0\u1226\0\u1254\0\u1282\0\u12b0"+
    "\0\u12de\0\u130c\0\u133a\0\u1368\0\u1396\0\u13c4\0\u13f2\0\u1420"+
    "\0\0\0\u144e\0\0\0\u147c\0\u14aa\0\u14d8\0\u1506\0\u1534"+
    "\0\u1562\0\u1590\0\u15be\0\u07ba\0\u15ec\0\u161a\0\u1648\0\u1676"+
    "\0\u07ba\0\u16a4\0\u07ba\0\u16d2\0\u1700\0\u172e\0\u175c\0\u178a"+
    "\0\0\0\u17b8\0\u17e6\0\0\0\u1814\0\u1842\0\u1870\0\u189e"+
    "\0\u07ba\0\u18cc\0\u18fa\0\u1928\0\u1956\0\u07ba\0\u1984\0\u07ba"+
    "\0\u19b2\0\u19e0\0\u1a0e\0\u1a3c\0\u1a6a\0\u1a98\0\u1ac6\0\u07ba"+
    "\0\u1af4\0\u07ba\0\u1b22\0\u1b50\0\u07ba\0\u1b7e\0\u1bac\0\u1bda"+
    "\0\u1c08\0\u1c36\0\u1c64\0\u17b8\0\0\0\u1c92\0\u1cc0\0\u1cee"+
    "\0\u1d1c\0\u07ba\0\u07ba\0\u1d4a\0\u1d78\0\u07ba\0\u1da6\0\u1dd4"+
    "\0\u1e02\0\u1e30\0\u1e5e\0\u1e8c\0\u1eba\0\u1ee8\0\u1f16\0\u1f44"+
    "\0\u1f72\0\u1fa0\0\u1fce\0\u07ba\0\u07ba\0\u07ba\0\u1ffc\0\u202a"+
    "\0\u2058\0\u2086\0\u20b4\0\u20e2\0\u2110\0\u213e\0\u07ba\0\u216c"+
    "\0\u219a\0\0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[242];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\56\0\1\13\1\14\1\15\1\16\1\17\1\20\4\13"+
    "\1\21\1\13\1\22\27\13\2\20\4\13\1\23\1\20"+
    "\1\13\1\20\3\24\1\25\11\24\1\26\40\24\15\27"+
    "\1\30\40\27\3\31\1\32\6\31\1\33\43\31\1\34"+
    "\1\35\1\36\1\37\1\34\1\40\50\34\1\41\1\42"+
    "\1\43\1\44\2\41\1\45\47\41\7\46\1\47\46\46"+
    "\1\50\2\51\41\50\1\52\1\53\10\50\1\54\2\55"+
    "\41\54\1\56\1\57\2\60\6\54\3\13\3\0\4\13"+
    "\1\0\1\13\1\61\27\13\2\0\4\13\2\0\1\13"+
    "\1\0\1\13\2\14\3\0\4\13\1\0\1\13\1\61"+
    "\27\13\2\0\4\13\2\0\1\13\1\0\1\13\1\14"+
    "\1\15\1\16\2\0\4\13\1\0\1\13\1\61\27\13"+
    "\2\0\4\13\2\0\1\13\3\0\2\16\56\0\1\62"+
    "\1\0\1\63\53\0\1\64\2\0\1\65\1\66\1\0"+
    "\1\67\1\70\2\0\1\71\1\72\2\0\1\73\2\66"+
    "\1\74\1\75\1\76\1\77\1\66\1\100\1\66\1\101"+
    "\1\102\5\66\1\103\4\0\1\66\1\104\4\0\4\13"+
    "\2\0\6\13\1\0\1\105\26\13\2\0\6\13\22\0"+
    "\1\20\35\0\15\25\1\106\55\25\1\106\2\25\1\107"+
    "\35\25\15\27\1\110\55\27\1\110\2\27\1\111\35\27"+
    "\12\32\1\112\55\32\1\112\7\32\1\113\33\32\5\114"+
    "\1\115\51\114\2\35\2\114\1\115\51\114\2\35\1\37"+
    "\1\114\1\115\55\114\1\116\50\114\6\117\1\120\50\117"+
    "\2\42\3\117\1\120\50\117\2\42\1\44\2\117\1\120"+
    "\55\117\1\121\47\117\7\46\1\122\55\46\1\123\46\46"+
    "\1\0\2\51\120\0\1\124\10\0\45\125\2\0\1\126"+
    "\7\125\2\55\42\125\2\0\1\126\6\125\4\13\2\0"+
    "\6\13\2\0\26\13\2\0\6\13\11\0\1\127\54\0"+
    "\1\130\53\0\1\131\111\0\1\132\25\0\2\66\1\0"+
    "\1\70\2\0\2\66\2\0\22\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\1\66\1\133\2\0\12\66"+
    "\1\134\7\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\12\66\1\135\7\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\1\66"+
    "\1\136\3\66\1\137\4\66\1\140\5\66\1\141\1\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\4\66\1\142\15\66\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\2\66\2\0\1\66\1\143\17\66"+
    "\1\144\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\12\66\1\145\7\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\1\66\1\146\2\0\1\147"+
    "\7\66\1\150\11\66\4\0\2\66\14\0\2\66\1\0"+
    "\1\70\2\0\2\66\2\0\12\66\1\151\7\66\4\0"+
    "\2\66\14\0\2\66\1\0\1\70\2\0\1\152\1\66"+
    "\2\0\22\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\1\153\21\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\11\66\1\154"+
    "\10\66\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\1\155\21\66\4\0\2\66\22\0\1\156"+
    "\2\0\1\157\20\0\1\160\13\0\15\27\1\110\2\27"+
    "\1\161\35\27\12\32\1\112\10\32\1\162\32\32\5\114"+
    "\1\163\50\114\5\0\1\164\50\0\6\117\1\165\54\117"+
    "\1\166\1\165\47\117\7\46\1\167\53\46\1\170\1\46"+
    "\1\167\46\46\47\171\1\0\6\171\7\0\1\172\70\0"+
    "\1\173\43\0\2\66\1\0\1\70\2\0\1\174\1\66"+
    "\2\0\22\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\15\66\1\175\4\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\6\66"+
    "\1\176\13\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\2\66\1\177\17\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\6\66"+
    "\1\200\13\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\7\66\1\201\12\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\10\66"+
    "\1\202\11\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\1\203\21\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\7\66\1\204"+
    "\12\66\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\3\66\1\205\16\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\11\66\1\206"+
    "\10\66\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\7\66\1\207\12\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\11\66\1\210"+
    "\10\66\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\4\66\1\211\15\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\1\212\1\66\2\0\22\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\2\66\1\213\17\66\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\2\66\2\0\15\66\1\214\4\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\3\66\1\215\16\66\4\0\2\66\23\0\1\216"+
    "\73\0\1\217\20\0\12\32\1\112\11\32\1\220\31\32"+
    "\5\117\1\221\1\165\47\117\5\46\1\222\1\46\1\167"+
    "\53\46\1\223\1\46\1\122\46\46\50\0\1\224\15\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\1\225\21\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\6\66\1\226\13\66\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\1\227\1\66\2\0\4\66\1\230"+
    "\1\66\1\231\12\66\1\232\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\2\66\2\0\1\233\21\66\4\0"+
    "\2\66\14\0\2\66\1\0\1\70\2\0\1\66\1\234"+
    "\2\0\22\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\1\235\21\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\5\66\1\236"+
    "\14\66\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\5\66\1\237\14\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\1\240\21\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\16\66\1\241\3\66\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\2\66\2\0\10\66\1\242\11\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\1\243"+
    "\1\66\2\0\22\66\4\0\2\66\14\0\2\66\1\0"+
    "\1\70\2\0\2\66\2\0\5\66\1\244\14\66\4\0"+
    "\2\66\14\0\2\66\1\0\1\70\2\0\2\66\2\0"+
    "\5\66\1\245\14\66\4\0\2\66\14\0\2\66\1\0"+
    "\1\70\2\0\2\66\2\0\4\66\1\246\15\66\4\0"+
    "\2\66\14\0\2\66\1\0\1\70\2\0\2\66\2\0"+
    "\1\247\21\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\21\66\1\250\4\0\2\66\22\0"+
    "\1\251\66\0\1\252\26\0\12\32\1\112\3\32\1\253"+
    "\37\32\5\46\1\254\1\46\1\122\46\46\51\0\1\255"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\1\66"+
    "\1\256\20\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\1\257\21\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\1\66\1\260\2\0\22\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\21\66\1\261\4\0\2\66\14\0\2\66\1\0"+
    "\1\70\2\0\2\66\2\0\1\262\21\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\11\66"+
    "\1\263\10\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\4\66\1\264\15\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\1\66"+
    "\1\265\20\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\2\66\1\266\17\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\17\66"+
    "\1\267\2\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\15\66\1\270\4\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\4\66"+
    "\1\271\15\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\16\66\1\272\3\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\3\66"+
    "\1\270\16\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\12\66\1\270\7\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\12\66"+
    "\1\273\7\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\15\66\1\274\4\66\4\0\2\66"+
    "\4\0\14\252\1\0\1\275\40\252\12\32\1\112\4\32"+
    "\1\276\36\32\26\0\1\277\37\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\10\66\1\300\11\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\7\66"+
    "\1\301\12\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\1\302\1\66\2\0\22\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\7\66\1\303"+
    "\12\66\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\15\66\1\304\4\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\21\66\1\305"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\2\66\1\306\17\66\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\2\66\2\0\2\66\1\307\17\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\11\66\1\310\10\66\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\2\66\2\0\4\66\1\311\15\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\7\66\1\312\12\66\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\2\66\2\0\12\66\1\313\7\66"+
    "\4\0\2\66\4\0\14\252\1\0\1\275\2\252\1\314"+
    "\35\252\12\32\1\112\3\32\1\315\37\32\32\0\1\316"+
    "\33\0\2\66\1\0\1\70\2\0\2\66\2\0\10\66"+
    "\1\317\11\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\10\66\1\320\11\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\1\321"+
    "\21\66\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\6\66\1\322\13\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\1\323\21\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\1\66\1\324\20\66\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\2\66\2\0\1\66\1\325\20\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\1\66"+
    "\1\326\2\0\22\66\4\0\2\66\14\0\2\66\1\0"+
    "\1\70\2\0\2\66\2\0\13\66\1\327\6\66\4\0"+
    "\2\66\13\0\1\330\56\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\4\66\1\331\15\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\4\66\1\332"+
    "\15\66\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\12\66\1\333\7\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\13\66\1\334"+
    "\6\66\4\0\2\66\14\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\2\66\1\270\17\66\4\0\2\66\14\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\1\335\21\66"+
    "\4\0\2\66\55\0\1\336\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\11\66\1\337\10\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\11\66"+
    "\1\340\10\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\7\66\1\341\12\66\4\0\2\66"+
    "\14\0\2\66\1\0\1\70\2\0\2\66\2\0\4\66"+
    "\1\342\15\66\4\0\2\66\14\0\2\66\1\0\1\70"+
    "\2\0\2\66\2\0\6\66\1\270\13\66\4\0\2\66"+
    "\26\0\1\343\43\0\2\66\1\0\1\70\2\0\2\66"+
    "\2\0\1\66\1\344\20\66\4\0\2\66\14\0\2\66"+
    "\1\0\1\70\2\0\2\66\2\0\1\66\1\345\20\66"+
    "\4\0\2\66\14\0\2\66\1\0\1\70\2\0\1\66"+
    "\1\346\2\0\22\66\4\0\2\66\14\0\2\66\1\0"+
    "\1\70\2\0\2\66\2\0\6\66\1\347\13\66\4\0"+
    "\2\66\31\0\1\350\40\0\2\66\1\0\1\70\2\0"+
    "\2\66\2\0\6\66\1\351\13\66\4\0\2\66\47\0"+
    "\1\352\22\0\2\66\1\0\1\70\2\0\2\66\2\0"+
    "\4\66\1\353\15\66\4\0\2\66\43\0\1\354\26\0"+
    "\2\66\1\0\1\70\2\0\2\66\2\0\1\66\1\355"+
    "\20\66\4\0\2\66\40\0\1\356\31\0\2\66\1\0"+
    "\1\70\2\0\2\66\2\0\14\66\1\357\5\66\4\0"+
    "\2\66\41\0\1\360\42\0\1\361\63\0\1\362\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8648];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\10\11\0\5\1\1\11\4\1\1\0\1\1\2\0"+
    "\1\1\1\0\13\1\2\0\1\11\2\1\1\11\3\1"+
    "\2\11\1\0\1\1\3\0\1\1\2\11\14\1\2\0"+
    "\1\11\1\0\1\11\4\0\1\1\5\0\1\11\2\0"+
    "\1\1\2\11\1\0\23\1\1\0\1\11\1\0\1\11"+
    "\1\0\1\1\1\11\1\0\1\11\2\0\2\11\1\0"+
    "\22\1\3\0\1\11\1\0\1\11\1\0\24\1\1\11"+
    "\2\0\1\11\1\0\17\1\3\0\15\1\1\11\1\0"+
    "\11\1\1\0\5\1\1\0\4\1\1\0\4\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\2\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[242];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF = false;

  /* user code: */
    private ByteStack stack = new ByteStack();
    private LexerInput input;
    private int parenBalanceInDirective = 0; //for directive arguments
    private int parameterExpressionLength = 0;
    private int pushBackCount = 0;
    //[\"][^\:\"]+[\:]{1}[^\:]
    private Pattern freezePhpPattern = Pattern.compile("[^\\:\\\"\\)]+[\\:]{1}[^\\:]", Pattern.CASE_INSENSITIVE);

    public BladeColoringLexer(LexerRestartInfo<? extends TokenId> info) {
        this.input = info.input();
        if(info.state() != null) {
            //reset state
            setState((LexerState) info.state(), parenBalanceInDirective);
        } else {
            //initial state
            stack.push(ST_HTML);
            zzState = ST_HTML;
            zzLexicalState = ST_HTML;
        }

    }

    public static final class LexerState  {
        final ByteStack stack;
        /** the current state of the DFA */
        final int zzState;
        /** the current lexical state */
        final int zzLexicalState;
        final int parenBalanceInDirective; 

        LexerState(ByteStack stack, int zzState, int zzLexicalState, int parenBalanceInDirective) {
            this.stack = stack;
            this.zzState = zzState;
            this.zzLexicalState = zzLexicalState;
            this.parenBalanceInDirective = parenBalanceInDirective;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (obj == null || obj.getClass() != this.getClass()) {
                return false;
            }
            LexerState state = (LexerState) obj;
            return (this.stack.equals(state.stack)
                && (this.zzState == state.zzState)
                );
        }

        @Override
        public int hashCode() {
            int hash = 11;
            hash = 31 * hash + this.zzState;
            hash = 31 * hash + this.zzLexicalState;
            hash = 31 * hash + this.parenBalanceInDirective;
            if (stack != null) {
                hash = 31 * hash + this.stack.hashCode();
            }
            return hash;
        }
    }

    public LexerState getState() {
        return new LexerState(stack.copyOf(), zzState, zzLexicalState, parenBalanceInDirective);
    }

    public void setState(LexerState state, int parenBalanceInDirective) {
        this.stack.copyFrom(state.stack);
        this.zzState = state.zzState;
        this.zzLexicalState = state.zzLexicalState;
        this.parenBalanceInDirective = state.parenBalanceInDirective;
    }

    protected int getZZLexicalState() {
        return zzLexicalState;
    }

    //other functions

    protected void pushBack(int i) {
        yypushback(i);
    }

    protected void popState() {
        yybegin(stack.pop());
    }

    protected void pushState(final int state) {
        stack.push(getZZLexicalState());
        yybegin(state);
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public BladeColoringLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public BladeColoringLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1756) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return input.readText().toString();
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
     return input.readText().charAt(pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return input.readLength();
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    input.backup(number);
    //zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public BladeTokenId findNextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    //int zzCurrentPosL;
    //int zzMarkedPosL;
    //int zzEndReadL = zzEndRead;
    //char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      //zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      //zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
      int tokenLength = 0;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
            zzInput = input.read();
            
            if(zzInput == LexerInput.EOF) {
                //end of input reached
                zzInput = YYEOF;
                break zzForAction;
                //notice: currently LexerInput.EOF == YYEOF
            }

          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            tokenLength = input.readLength();
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      if(zzInput != YYEOF) {
         input.backup(input.readLength() - tokenLength);
      }

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 56: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
       return BladeTokenId.T_BLADE_HAS_SECTION;
          }
        case 60: break;
        case 3: 
          { String yytext = yytext();
	//whitespace
    return BladeTokenId.NEWLINE;
          }
        case 61: break;
        case 39: 
          { return BladeTokenId.T_BLADE_SHOW;
          }
        case 62: break;
        case 20: 
          { if (yylength() == 2){
	    popState(); 
		return BladeTokenId.T_CLOSE_PHP;
	}
	yypushback(2);
    return BladeTokenId.T_PHP_ECHO;
          }
        case 63: break;
        case 10: 
          { parenBalanceInDirective = 0;
   popState();
   return BladeTokenId.T_BLADE_RPAREN;
          }
        case 64: break;
        case 26: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_IF;
          }
        case 65: break;
        case 55: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_FOREACH;
          }
        case 66: break;
        case 7: 
          { if (yylength() > 0){
        yypushback(1);
    }
    popState();
          }
        case 67: break;
        case 29: 
          { String yytext = yytext();
    if (yylength() == 2){
    	popState();
    	return BladeTokenId.T_BLADE_CLOSE_ECHO;
    }
    yypushback(2);

    Matcher matcher = freezePhpPattern.matcher(yytext);
    if(matcher.find()) {
        return BladeTokenId.T_HTML;
    }
    return BladeTokenId.T_BLADE_PHP_ECHO;
          }
        case 68: break;
        case 33: 
          { pushState(ST_BLADE_PHP);
    return BladeTokenId.T_BLADE_PHP_OPEN;
          }
        case 69: break;
        case 12: 
          { String text = yytext();
    parameterExpressionLength+= yylength();
          }
        case 70: break;
        case 44: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_YIELD;
          }
        case 71: break;
        case 40: 
          { return BladeTokenId.T_BLADE_STOP;
          }
        case 72: break;
        case 19: 
          { if (yylength() == 2){
       popState();
       return BladeTokenId.T_CLOSE_PHP;
    }
    yypushback(2);
    return BladeTokenId.T_PHP;
          }
        case 73: break;
        case 9: 
          { pushState(ST_BLADE_PARAMETER_EXPRESSION);
   parenBalanceInDirective = 1;
   parameterExpressionLength = 0;
   return BladeTokenId.T_BLADE_LPAREN;
          }
        case 74: break;
        case 49: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_ELSEIF;
          }
        case 75: break;
        case 43: 
          { return BladeTokenId.T_BLADE_ENDIF;
          }
        case 76: break;
        case 28: 
          { if (yylength() == 2){
       popState();
       return BladeTokenId.T_CLOSE_PHP;
    }
    yypushback(2);
    return BladeTokenId.T_PHP_ECHO;
          }
        case 77: break;
        case 45: 
          { //css directives
    return BladeTokenId.T_HTML;
          }
        case 78: break;
        case 36: 
          { popState();
    return BladeTokenId.T_BLADE_CLOSE_COMMENT;
          }
        case 79: break;
        case 25: 
          { //escape expression
    return BladeTokenId.T_HTML;
          }
        case 80: break;
        case 17: 
          { //escape directive rule
    return BladeTokenId.T_HTML;
          }
        case 81: break;
        case 18: 
          { //email format
    return BladeTokenId.T_HTML;
          }
        case 82: break;
        case 2: 
          { String yytext = yytext();
	//whitespace
    return BladeTokenId.WHITESPACE;
          }
        case 83: break;
        case 30: 
          { String yytext = yytext();
    popState();
    return BladeTokenId.T_BLADE_CLOSE_ECHO_ESCAPED;
          }
        case 84: break;
        case 50: 
          { return BladeTokenId.T_XML;
          }
        case 85: break;
        case 38: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_EACH;
          }
        case 86: break;
        case 34: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_FOR;
          }
        case 87: break;
        case 46: 
          { return BladeTokenId.T_BLADE_PARENT;
          }
        case 88: break;
        case 15: 
          { String yytext = yytext();
    pushState(ST_BLADE_ECHO);
    return BladeTokenId.T_BLADE_OPEN_ECHO;
          }
        case 89: break;
        case 47: 
          { return BladeTokenId.T_BLADE_ENDPHP;
          }
        case 90: break;
        case 51: 
          { String ttext = yytext();
    popState();
    if (yylength() == "@endphp".length()){
        return BladeTokenId.T_BLADE_ENDPHP;
    }
    
    yypushback("@endphp".length());
    return BladeTokenId.T_BLADE_PHP;
          }
        case 91: break;
        case 8: 
          { return BladeTokenId.WHITESPACE;
          }
        case 92: break;
        case 42: 
          { yypushback(4);
    return BladeTokenId.T_BLADE_COMMENT;
          }
        case 93: break;
        case 35: 
          { String yytext = yytext();
    if (yylength() == 3){
    	popState();
    	return BladeTokenId.T_BLADE_CLOSE_ECHO;
    }
    yypushback(3);
    Matcher matcher = freezePhpPattern.matcher(yytext);
    if(matcher.find()) {
        return BladeTokenId.T_HTML;
    }
    return BladeTokenId.T_BLADE_PHP_ECHO;
          }
        case 94: break;
        case 14: 
          { parenBalanceInDirective--;
   if (parenBalanceInDirective == 0) {
      yypushback(1);
      popState();
      return BladeTokenId.T_BLADE_PHP_EXPRESSION;
   }
          }
        case 95: break;
        case 32: 
          { pushState(ST_COMMENT);
    return BladeTokenId.T_BLADE_OPEN_COMMENT;
          }
        case 96: break;
        case 54: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
       return BladeTokenId.T_BLADE_SECTION;
          }
        case 97: break;
        case 52: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_EXTENDS;
          }
        case 98: break;
        case 24: 
          { String yytext = yytext();
    pushState(ST_BLADE_ECHO_ESCAPED);
    return BladeTokenId.T_BLADE_OPEN_ECHO_ESCAPED;
          }
        case 99: break;
        case 58: 
          { return BladeTokenId.T_BLADE_ENDFOREACH;
          }
        case 100: break;
        case 53: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_INCLUDE;
          }
        case 101: break;
        case 11: 
          { parameterExpressionLength =0;
          }
        case 102: break;
        case 57: 
          { return BladeTokenId.T_BLADE_ENDSECTION;
          }
        case 103: break;
        case 27: 
          { pushState(ST_PHP_ECHO);
    return BladeTokenId.T_PHP_OPEN_ECHO;
          }
        case 104: break;
        case 31: 
          { //php lexer embedding freeze issue when you type / delete a double colon at the start of the script
    if (parameterExpressionLength == 0) {
        popState();
        popState();
        parameterExpressionLength = 0;
        return  BladeTokenId.T_HTML;
    }
          }
        case 105: break;
        case 41: 
          { pushState(ST_PHP);
    return BladeTokenId.T_OPEN_PHP_SCRIPT;
          }
        case 106: break;
        case 16: 
          { String ttext = yytext();
    pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
    return BladeTokenId.T_BLADE_DIRECTIVE;
          }
        case 107: break;
        case 23: 
          { //incomplete comment
    return BladeTokenId.T_HTML;
          }
        case 108: break;
        case 59: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
       return BladeTokenId.T_BLADE_SECTION_MISSING;
          }
        case 109: break;
        case 21: 
          { String yytext = yytext();
    popState();
    return BladeTokenId.T_BLADE_CLOSE_ECHO;
          }
        case 110: break;
        case 5: 
          { //no break;
    parameterExpressionLength += yylength();
          }
        case 111: break;
        case 48: 
          { return BladeTokenId.T_BLADE_ENDFOR;
          }
        case 112: break;
        case 37: 
          { return BladeTokenId.T_BLADE_ELSE;
          }
        case 113: break;
        case 6: 
          { String yytext = yytext();
    popState();
    return BladeTokenId.T_HTML;
          }
        case 114: break;
        case 22: 
          { parenBalanceInDirective = 0;
   popState();
   return BladeTokenId.T_EMPTY_EXPRESSION;
          }
        case 115: break;
        case 13: 
          { parenBalanceInDirective++;
          }
        case 116: break;
        case 4: 
          { //skipp
          }
        case 117: break;
        case 1: 
          { return  BladeTokenId.T_HTML;
          }
        case 118: break;
        default: 
          if (zzInput == YYEOF) 
            //zzAtEOF = true;
            switch (zzLexicalState) {
            case ST_PHP: {
              if (input.readLength() > 0) {
    input.backup(1);  // backup eof
    return BladeTokenId.T_PHP;
  }
  else {
      return null;
  }
            }
            case 243: break;
            case ST_COMMENT: {
              popState();
  if (yylength() > 0){
    return BladeTokenId.T_HTML;
  }
            }
            case 244: break;
            default:
              {         if(input.readLength() > 0) {
            String yytext = yytext();
            // backup eof
            input.backup(1);
            //and return the text as error token
             return BladeTokenId.T_HTML;
        } else {
            return null;
        }
 }
            }
          
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
