/* The following code was generated by JFlex 1.4.3 on 6/18/23, 7:51 AM */

   /*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 2016 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2016 Sun Microsystems, Inc.
 */

package org.netbeans.modules.php.blade.editor.lexer;

import org.netbeans.api.lexer.TokenId;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.netbeans.spi.lexer.LexerInput;
import org.netbeans.spi.lexer.LexerRestartInfo;
import org.netbeans.modules.php.blade.editor.common.ByteStack;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 6/18/23, 7:51 AM from the specification file
 * <tt>C:/LOCAL_P5_APPS/lmc/blade-php/tools/BladeColoringLexer.flex</tt>
 */
public class BladeColoringLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = LexerInput.EOF;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int ST_BLADE_PARAMETER_EXPRESSION = 26;
  public static final int ST_LOOKING_FOR_PARAMETER_EXPRESSION = 24;
  public static final int ST_AFTER_DIRECTIVE_ARG = 30;
  public static final int ST_PHP = 4;
  public static final int ST_COMMENT = 20;
  public static final int ST_BLADE_ARGUMENT = 28;
  public static final int ST_BLADE_PHP = 10;
  public static final int ST_BLADE_ECHO = 12;
  public static final int ST_DIRECTIVE = 18;
  public static final int ST_BLADE_ECHO_ESCAPED = 16;
  public static final int YYINITIAL = 0;
  public static final int ST_VALIDATE_BLADE_ECHO = 14;
  public static final int ST_INLINE_PHP = 8;
  public static final int ST_PHP_ECHO = 6;
  public static final int ST_HTML = 2;
  public static final int ST_CLOSE_BLADE_PHP = 22;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  0,  0,  4,  4,  5,  5,  0,  0, 
     6,  6,  0,  0,  7,  7,  0,  0,  8,  8,  9,  9,  0,  0,  0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\2\0\1\2\22\0\1\47\1\6\1\46\2\0"+
    "\1\55\2\0\1\44\1\45\2\54\1\0\1\7\1\13\1\53\12\11"+
    "\1\50\1\0\1\14\1\21\1\20\1\15\1\12\1\34\1\51\1\31"+
    "\1\24\1\22\1\43\1\36\1\17\1\26\1\10\1\52\1\27\1\35"+
    "\1\23\1\33\1\16\1\10\1\37\1\30\1\32\1\41\1\10\1\40"+
    "\1\42\1\25\1\10\4\0\1\10\1\0\1\34\1\51\1\31\1\24"+
    "\1\22\1\43\1\36\1\17\1\26\1\10\1\52\1\27\1\35\1\23"+
    "\1\33\1\16\1\10\1\37\1\30\1\32\1\41\1\10\1\40\1\42"+
    "\1\25\1\10\1\4\1\56\1\5\1\0\53\10\1\10\12\10\1\10"+
    "\4\10\1\10\5\10\27\10\1\10\37\10\1\10\10\10\u01c2\10\4\0"+
    "\14\10\16\0\5\10\7\0\1\10\1\0\1\10\201\0\5\10\1\0"+
    "\2\10\2\0\4\10\1\0\1\10\6\0\1\10\1\0\3\10\1\0"+
    "\1\10\1\0\24\10\1\0\123\10\1\0\213\10\10\0\246\10\1\0"+
    "\46\10\2\0\1\10\6\0\51\10\107\0\33\10\4\0\4\10\55\0"+
    "\53\10\25\0\12\11\4\0\2\10\1\0\143\10\1\0\1\10\17\0"+
    "\2\10\7\0\2\10\12\11\3\10\2\0\1\10\20\0\1\10\1\0"+
    "\36\10\35\0\131\10\13\0\1\10\16\0\12\11\41\10\11\0\2\10"+
    "\4\0\1\10\5\0\26\10\4\0\1\10\11\0\1\10\3\0\1\10"+
    "\27\0\31\10\7\0\13\10\65\0\25\10\1\0\22\10\74\0\66\10"+
    "\3\0\1\10\22\0\1\10\7\0\12\10\4\0\12\11\1\0\20\10"+
    "\4\0\10\10\2\0\2\10\2\0\26\10\1\0\7\10\1\0\1\10"+
    "\3\0\4\10\3\0\1\10\20\0\1\10\15\0\2\10\1\0\3\10"+
    "\4\0\12\11\2\10\12\0\1\10\10\0\6\10\4\0\2\10\2\0"+
    "\26\10\1\0\7\10\1\0\2\10\1\0\2\10\1\0\2\10\37\0"+
    "\4\10\1\0\1\10\7\0\12\11\2\0\3\10\20\0\11\10\1\0"+
    "\3\10\1\0\26\10\1\0\7\10\1\0\2\10\1\0\5\10\3\0"+
    "\1\10\22\0\1\10\17\0\2\10\4\0\12\11\11\0\1\10\13\0"+
    "\10\10\2\0\2\10\2\0\26\10\1\0\7\10\1\0\2\10\1\0"+
    "\5\10\3\0\1\10\36\0\2\10\1\0\3\10\4\0\12\11\1\0"+
    "\1\10\21\0\1\10\1\0\6\10\3\0\3\10\1\0\4\10\3\0"+
    "\2\10\1\0\1\10\1\0\2\10\3\0\2\10\3\0\3\10\3\0"+
    "\14\10\26\0\1\10\25\0\12\11\25\0\10\10\1\0\3\10\1\0"+
    "\27\10\1\0\20\10\3\0\1\10\32\0\3\10\5\0\2\10\4\0"+
    "\12\11\20\0\1\10\4\0\10\10\1\0\3\10\1\0\27\10\1\0"+
    "\12\10\1\0\5\10\3\0\1\10\40\0\1\10\1\0\2\10\4\0"+
    "\12\11\1\0\2\10\21\0\11\10\1\0\3\10\1\0\51\10\2\0"+
    "\1\10\20\0\1\10\5\0\3\10\10\0\3\10\4\0\12\11\12\0"+
    "\6\10\5\0\22\10\3\0\30\10\1\0\11\10\1\0\1\10\2\0"+
    "\7\10\37\0\12\11\21\0\60\10\1\0\2\10\14\0\7\10\11\0"+
    "\12\11\47\0\2\10\1\0\1\10\1\0\5\10\1\0\30\10\1\0"+
    "\1\10\1\0\12\10\1\0\2\10\11\0\1\10\2\0\5\10\1\0"+
    "\1\10\11\0\12\11\2\0\4\10\40\0\1\10\37\0\12\11\26\0"+
    "\10\10\1\0\44\10\33\0\5\10\163\0\53\10\24\0\1\10\12\11"+
    "\6\0\6\10\4\0\4\10\3\0\1\10\3\0\2\10\7\0\3\10"+
    "\4\0\15\10\14\0\1\10\1\0\12\11\6\0\46\10\1\0\1\10"+
    "\5\0\1\10\2\0\53\10\1\0\u014d\10\1\0\4\10\2\0\7\10"+
    "\1\0\1\10\1\0\4\10\2\0\51\10\1\0\4\10\2\0\41\10"+
    "\1\0\4\10\2\0\7\10\1\0\1\10\1\0\4\10\2\0\17\10"+
    "\1\0\71\10\1\0\4\10\2\0\103\10\45\0\20\10\20\0\126\10"+
    "\2\0\6\10\3\0\u026c\10\2\0\21\10\1\0\32\10\5\0\113\10"+
    "\6\0\10\10\7\0\15\10\1\0\4\10\16\0\22\10\16\0\22\10"+
    "\16\0\15\10\1\0\3\10\17\0\64\10\43\0\1\10\4\0\1\10"+
    "\3\0\12\11\46\0\12\11\6\0\131\10\7\0\5\10\2\0\42\10"+
    "\1\0\1\10\5\0\106\10\12\0\37\10\47\0\12\11\36\10\2\0"+
    "\5\10\13\0\54\10\4\0\32\10\6\0\12\11\46\0\27\10\11\0"+
    "\65\10\53\0\12\11\6\0\12\11\15\0\1\10\135\0\57\10\21\0"+
    "\7\10\4\0\12\11\51\0\36\10\15\0\2\10\12\11\54\10\32\0"+
    "\44\10\34\0\12\11\3\0\3\10\12\11\44\10\2\0\11\10\7\0"+
    "\53\10\2\0\3\10\51\0\4\10\1\0\6\10\1\0\2\10\3\0"+
    "\1\10\5\0\300\10\100\0\u0116\10\2\0\6\10\2\0\46\10\2\0"+
    "\6\10\2\0\10\10\1\0\1\10\1\0\1\10\1\0\1\10\1\0"+
    "\37\10\2\0\65\10\1\0\7\10\1\0\1\10\3\0\3\10\1\0"+
    "\7\10\3\0\4\10\2\0\6\10\4\0\15\10\5\0\3\10\1\0"+
    "\7\10\164\0\1\10\15\0\1\10\20\0\15\10\145\0\1\10\4\0"+
    "\1\10\2\0\12\10\1\0\1\10\3\0\5\10\6\0\1\10\1\0"+
    "\1\10\1\0\1\10\1\0\4\10\1\0\13\10\2\0\4\10\5\0"+
    "\5\10\4\0\1\10\64\0\2\10\u0a7b\0\57\10\1\0\57\10\1\0"+
    "\205\10\6\0\4\10\3\0\2\10\14\0\46\10\1\0\1\10\5\0"+
    "\1\10\2\0\70\10\7\0\1\10\20\0\27\10\11\0\7\10\1\0"+
    "\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0"+
    "\7\10\1\0\7\10\120\0\1\10\u01d5\0\2\10\52\0\5\10\5\0"+
    "\2\10\4\0\126\10\6\0\3\10\1\0\132\10\1\0\4\10\5\0"+
    "\53\10\1\0\136\10\21\0\40\10\60\0\20\10\u0200\0\u19c0\10\100\0"+
    "\u51fd\10\3\0\u048d\10\103\0\56\10\2\0\u010d\10\3\0\20\10\12\11"+
    "\2\10\24\0\57\10\20\0\37\10\2\0\106\10\61\0\11\10\2\0"+
    "\147\10\2\0\65\10\2\0\11\10\52\0\15\10\1\0\3\10\1\0"+
    "\4\10\1\0\27\10\35\0\64\10\16\0\62\10\34\0\12\11\30\0"+
    "\6\10\3\0\1\10\1\0\2\10\1\0\12\11\34\10\12\0\27\10"+
    "\31\0\35\10\7\0\57\10\34\0\1\10\12\11\6\0\5\10\1\0"+
    "\12\10\12\11\5\10\1\0\51\10\27\0\3\10\1\0\10\10\4\0"+
    "\12\11\6\0\27\10\3\0\1\10\3\0\62\10\1\0\1\10\3\0"+
    "\2\10\2\0\5\10\2\0\1\10\1\0\1\10\30\0\3\10\2\0"+
    "\13\10\7\0\3\10\14\0\6\10\2\0\6\10\2\0\6\10\11\0"+
    "\7\10\1\0\7\10\1\0\53\10\1\0\16\10\6\0\163\10\15\0"+
    "\12\11\6\0\u2ba4\10\14\0\27\10\4\0\61\10\u2104\0\u016e\10\2\0"+
    "\152\10\46\0\7\10\14\0\5\10\5\0\1\10\1\0\12\10\1\0"+
    "\15\10\1\0\5\10\1\0\1\10\1\0\2\10\1\0\2\10\1\0"+
    "\154\10\41\0\u016b\10\22\0\100\10\2\0\66\10\50\0\14\10\164\0"+
    "\5\10\1\0\207\10\23\0\12\11\7\0\32\10\6\0\32\10\13\0"+
    "\131\10\3\0\6\10\2\0\6\10\2\0\6\10\2\0\3\10\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\12\0\1\1\1\2\2\3\5\1\1\4\1\0\1\4"+
    "\2\0\1\4\1\0\2\4\1\5\2\6\2\4\1\5"+
    "\2\6\1\4\2\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\13\1\15\1\16\1\14\1\0\1\17\3\0"+
    "\1\20\1\21\1\22\14\20\2\0\1\23\1\0\1\24"+
    "\4\0\1\25\5\0\1\26\2\0\1\27\1\30\1\31"+
    "\1\0\11\20\1\32\11\20\1\0\1\33\1\0\1\34"+
    "\1\0\2\35\1\0\1\36\2\0\1\37\1\0\1\40"+
    "\1\0\1\41\17\20\1\42\1\20\3\0\1\43\1\0"+
    "\1\44\2\0\6\20\1\45\1\46\4\20\1\47\1\20"+
    "\1\50\5\20\1\51\2\0\1\52\2\0\3\20\1\53"+
    "\4\20\1\54\1\20\1\55\4\20\4\0\1\56\1\20"+
    "\1\57\1\20\1\60\1\61\6\20\1\62\1\63\2\0"+
    "\3\20\1\64\1\65\1\66\1\20\1\67\1\20\2\0"+
    "\5\20\2\0\4\20\2\0\1\70\1\71\1\72\1\20"+
    "\2\0\1\20\1\0\1\20\1\0\1\20\1\0\1\73"+
    "\2\0\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[252];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\0"+
    "\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u034e\0\u037d\0\u03ac\0\u03db"+
    "\0\u040a\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u0468\0\u04f5"+
    "\0\u0524\0\u0553\0\u0582\0\u0524\0\u05b1\0\u05e0\0\u060f\0\0"+
    "\0\u063e\0\u066d\0\0\0\u069c\0\u06cb\0\0\0\u069c\0\0"+
    "\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\0"+
    "\0\0\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d"+
    "\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0a48\0\u0a77\0\u037d\0\0"+
    "\0\u0aa6\0\0\0\u0439\0\u0ad5\0\u0468\0\u0b04\0\u0b33\0\u0524"+
    "\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\0\0\u069c\0\u0c1e\0\u0c4d"+
    "\0\0\0\0\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67"+
    "\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0814\0\u0e52\0\u0e81\0\u0eb0"+
    "\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9\0\0"+
    "\0\u1028\0\0\0\u1057\0\u0b33\0\0\0\u1086\0\0\0\u10b5"+
    "\0\u10e4\0\0\0\u1113\0\0\0\u1142\0\u0814\0\u1171\0\u11a0"+
    "\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b\0\u12ba\0\u12e9\0\u1318"+
    "\0\u1347\0\u1376\0\u13a5\0\u13d4\0\u1403\0\u1432\0\u1461\0\u1490"+
    "\0\u14bf\0\u14ee\0\0\0\u151d\0\0\0\u154c\0\u157b\0\u15aa"+
    "\0\u15d9\0\u1608\0\u1637\0\u1666\0\u1695\0\u16c4\0\u0814\0\u16f3"+
    "\0\u1722\0\u1751\0\u1780\0\u0814\0\u17af\0\u0814\0\u17de\0\u180d"+
    "\0\u183c\0\u186b\0\u189a\0\0\0\u18c9\0\u18f8\0\0\0\u1927"+
    "\0\u1956\0\u1985\0\u19b4\0\u19e3\0\u0814\0\u1a12\0\u1a41\0\u1a70"+
    "\0\u1a9f\0\u0814\0\u1ace\0\u0814\0\u1afd\0\u1b2c\0\u1b5b\0\u1b8a"+
    "\0\u1bb9\0\u1be8\0\u1c17\0\u1c46\0\u0814\0\u1c75\0\u0814\0\u1ca4"+
    "\0\u1cd3\0\u0814\0\u1d02\0\u1d31\0\u1d60\0\u1d8f\0\u1dbe\0\u1ded"+
    "\0\u18c9\0\0\0\u1e1c\0\u1e4b\0\u1e7a\0\u1ea9\0\u1ed8\0\u0814"+
    "\0\u0814\0\u1f07\0\u1f36\0\u0814\0\u1f65\0\u1f94\0\u1fc3\0\u1ff2"+
    "\0\u2021\0\u2050\0\u207f\0\u20ae\0\u20dd\0\u210c\0\u213b\0\u216a"+
    "\0\u2199\0\u21c8\0\u21f7\0\u2226\0\u0814\0\u0814\0\u0814\0\u2255"+
    "\0\u2284\0\u22b3\0\u22e2\0\u2311\0\u2340\0\u236f\0\u239e\0\u23cd"+
    "\0\u0814\0\u23fc\0\u242b\0\0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[252];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\57\0\1\13\1\14\1\15\1\16\1\17\1\20\4\13"+
    "\1\21\1\13\1\22\27\13\2\20\1\13\1\14\3\13"+
    "\1\23\1\20\1\13\1\20\3\24\1\25\11\24\1\26"+
    "\41\24\15\27\1\30\41\27\3\31\1\32\6\31\1\33"+
    "\44\31\1\34\1\35\1\36\1\37\1\34\1\40\41\34"+
    "\1\35\7\34\1\41\1\42\1\43\1\44\2\41\1\45"+
    "\40\41\1\42\7\41\7\46\1\47\47\46\1\50\2\51"+
    "\41\50\1\52\1\53\1\50\1\51\7\50\1\54\2\55"+
    "\12\54\1\56\26\54\1\57\1\60\1\56\1\61\1\56"+
    "\6\54\3\13\3\0\4\13\1\0\1\13\1\62\27\13"+
    "\2\0\5\13\2\0\1\13\1\0\1\13\2\14\3\0"+
    "\4\13\1\0\1\13\1\62\27\13\2\0\1\13\1\14"+
    "\3\13\2\0\1\13\1\0\1\13\1\14\1\15\1\16"+
    "\2\0\4\13\1\0\1\13\1\62\27\13\2\0\1\13"+
    "\1\14\3\13\2\0\1\13\3\0\2\16\57\0\1\63"+
    "\1\0\1\64\54\0\1\65\2\0\1\66\1\67\1\0"+
    "\1\70\1\71\2\0\1\72\1\73\2\0\1\74\2\67"+
    "\1\75\1\76\1\77\1\100\1\67\1\101\1\67\1\102"+
    "\1\103\5\67\1\104\5\0\1\67\1\105\4\0\4\13"+
    "\2\0\6\13\1\0\1\106\26\13\2\0\7\13\22\0"+
    "\1\20\36\0\15\25\1\107\56\25\1\107\2\25\1\110"+
    "\36\25\15\27\1\111\56\27\1\111\2\27\1\112\36\27"+
    "\12\32\1\113\56\32\1\113\7\32\1\114\34\32\5\115"+
    "\1\116\52\115\2\35\2\115\1\116\41\115\1\35\10\115"+
    "\2\35\1\37\1\115\1\116\41\115\1\35\14\115\1\117"+
    "\51\115\6\120\1\121\51\120\2\42\3\120\1\121\40\120"+
    "\1\42\10\120\2\42\1\44\2\120\1\121\40\120\1\42"+
    "\15\120\1\122\50\120\7\46\1\123\56\46\1\124\47\46"+
    "\1\0\2\51\44\0\1\51\54\0\1\125\11\0\15\126"+
    "\1\0\27\126\3\0\1\127\7\126\2\55\12\126\1\0"+
    "\27\126\2\0\1\61\1\127\6\126\1\0\2\61\44\0"+
    "\1\61\7\0\4\13\2\0\6\13\2\0\26\13\2\0"+
    "\7\13\11\0\1\130\55\0\1\131\54\0\1\132\112\0"+
    "\1\133\26\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\22\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\1\67\1\134\2\0\12\67\1\135\7\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\2\67\2\0\12\67"+
    "\1\136\7\67\5\0\2\67\14\0\2\67\1\0\1\71"+
    "\2\0\2\67\2\0\1\67\1\137\3\67\1\140\4\67"+
    "\1\141\5\67\1\142\1\67\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\4\67\1\143\15\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\1\67\1\144\17\67\1\145\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\12\67\1\146"+
    "\7\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\1\67\1\147\2\0\1\150\7\67\1\151\11\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\12\67\1\152\7\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\1\153\1\67\2\0\22\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\2\67\2\0\1\154"+
    "\21\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\11\67\1\155\10\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\1\156\21\67"+
    "\5\0\2\67\22\0\1\157\2\0\1\160\20\0\1\161"+
    "\14\0\15\27\1\111\2\27\1\162\36\27\12\32\1\113"+
    "\10\32\1\163\33\32\5\115\1\164\51\115\5\0\1\165"+
    "\51\0\6\120\1\166\55\120\1\167\1\166\50\120\7\46"+
    "\1\170\54\46\1\171\1\46\1\170\47\46\50\172\1\173"+
    "\6\172\7\0\1\174\71\0\1\175\44\0\2\67\1\0"+
    "\1\71\2\0\1\176\1\67\2\0\22\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\2\67\2\0\15\67"+
    "\1\177\4\67\5\0\2\67\14\0\2\67\1\0\1\71"+
    "\2\0\2\67\2\0\6\67\1\200\13\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\2\67\2\0\2\67"+
    "\1\201\17\67\5\0\2\67\14\0\2\67\1\0\1\71"+
    "\2\0\2\67\2\0\6\67\1\202\13\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\2\67\2\0\7\67"+
    "\1\203\12\67\5\0\2\67\14\0\2\67\1\0\1\71"+
    "\2\0\2\67\2\0\10\67\1\204\11\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\2\67\2\0\1\205"+
    "\21\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\7\67\1\206\12\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\3\67\1\207"+
    "\16\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\11\67\1\210\10\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\7\67\1\211"+
    "\12\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\11\67\1\212\10\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\4\67\1\213"+
    "\15\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\1\214\1\67\2\0\22\67\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\2\67\1\215\17\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\15\67\1\216\4\67\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\3\67\1\217\16\67"+
    "\5\0\2\67\23\0\1\220\74\0\1\221\21\0\12\32"+
    "\1\113\11\32\1\222\32\32\5\120\1\223\1\166\50\120"+
    "\5\46\1\224\1\46\1\170\54\46\1\225\1\46\1\123"+
    "\47\46\50\0\1\226\57\0\1\227\15\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\1\230\21\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\2\67\2\0\6\67"+
    "\1\231\13\67\5\0\2\67\14\0\2\67\1\0\1\71"+
    "\2\0\1\232\1\67\2\0\4\67\1\233\1\67\1\234"+
    "\12\67\1\235\5\0\2\67\14\0\2\67\1\0\1\71"+
    "\2\0\2\67\2\0\1\236\21\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\1\67\1\237\2\0\22\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\1\240\21\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\5\67\1\241\14\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\5\67\1\242\14\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\1\243\21\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\2\67\2\0\16\67"+
    "\1\244\3\67\5\0\2\67\14\0\2\67\1\0\1\71"+
    "\2\0\2\67\2\0\10\67\1\245\11\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\1\246\1\67\2\0"+
    "\22\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\5\67\1\247\14\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\5\67\1\250"+
    "\14\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\4\67\1\251\15\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\1\252\21\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\21\67\1\253\5\0\2\67\22\0\1\254\67\0"+
    "\1\255\27\0\12\32\1\113\3\32\1\256\40\32\5\46"+
    "\1\257\1\46\1\123\47\46\50\172\1\260\6\172\52\0"+
    "\1\261\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\1\67\1\262\20\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\1\263\21\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\1\67\1\264\2\0"+
    "\22\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\21\67\1\265\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\1\266\21\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\11\67\1\267\10\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\4\67\1\270\15\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\1\67\1\271\20\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\2\67\1\272\17\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\17\67\1\273\2\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\15\67\1\274\4\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\4\67\1\275\15\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\16\67\1\276\3\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\3\67\1\274\16\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\12\67\1\274\7\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\12\67\1\277\7\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\15\67\1\300\4\67\5\0"+
    "\2\67\4\0\14\255\1\0\1\301\41\255\12\32\1\113"+
    "\4\32\1\302\37\32\50\172\1\303\6\172\26\0\1\304"+
    "\40\0\2\67\1\0\1\71\2\0\2\67\2\0\10\67"+
    "\1\305\11\67\5\0\2\67\14\0\2\67\1\0\1\71"+
    "\2\0\2\67\2\0\7\67\1\306\12\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\1\307\1\67\2\0"+
    "\22\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\7\67\1\310\12\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\15\67\1\311"+
    "\4\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\21\67\1\312\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\2\67\1\313\17\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\2\67\1\314\17\67\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\11\67\1\315\10\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\4\67\1\316\15\67\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\7\67\1\317\12\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\12\67\1\320\7\67\5\0\2\67\4\0\14\255"+
    "\1\0\1\301\2\255\1\321\36\255\12\32\1\113\3\32"+
    "\1\322\40\32\50\172\1\323\6\172\32\0\1\324\34\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\10\67\1\325"+
    "\11\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\10\67\1\326\11\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\1\327\21\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\6\67\1\330\13\67\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\1\331\21\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\1\67\1\332\20\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\1\67\1\333\20\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\1\67\1\334"+
    "\2\0\22\67\5\0\2\67\14\0\2\67\1\0\1\71"+
    "\2\0\2\67\2\0\13\67\1\335\6\67\5\0\2\67"+
    "\4\0\50\172\1\336\6\172\7\0\1\337\57\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\4\67\1\340\15\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\4\67\1\341\15\67\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\12\67\1\342\7\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\13\67\1\343\6\67\5\0\2\67\14\0\2\67"+
    "\1\0\1\71\2\0\2\67\2\0\2\67\1\274\17\67"+
    "\5\0\2\67\14\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\1\344\21\67\5\0\2\67\4\0\50\172\1\345"+
    "\6\172\52\0\1\346\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\11\67\1\347\10\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\11\67\1\350"+
    "\10\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\7\67\1\351\12\67\5\0\2\67\14\0"+
    "\2\67\1\0\1\71\2\0\2\67\2\0\4\67\1\352"+
    "\15\67\5\0\2\67\14\0\2\67\1\0\1\71\2\0"+
    "\2\67\2\0\6\67\1\274\13\67\5\0\2\67\4\0"+
    "\50\172\1\353\6\172\22\0\1\354\44\0\2\67\1\0"+
    "\1\71\2\0\2\67\2\0\1\67\1\355\20\67\5\0"+
    "\2\67\14\0\2\67\1\0\1\71\2\0\2\67\2\0"+
    "\1\67\1\356\20\67\5\0\2\67\14\0\2\67\1\0"+
    "\1\71\2\0\1\67\1\357\2\0\22\67\5\0\2\67"+
    "\14\0\2\67\1\0\1\71\2\0\2\67\2\0\6\67"+
    "\1\360\13\67\5\0\2\67\4\0\50\172\1\361\6\172"+
    "\25\0\1\362\41\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\6\67\1\363\13\67\5\0\2\67\4\0\50\172"+
    "\1\0\6\172\43\0\1\364\23\0\2\67\1\0\1\71"+
    "\2\0\2\67\2\0\4\67\1\365\15\67\5\0\2\67"+
    "\43\0\1\366\27\0\2\67\1\0\1\71\2\0\2\67"+
    "\2\0\1\67\1\367\20\67\5\0\2\67\40\0\1\370"+
    "\32\0\2\67\1\0\1\71\2\0\2\67\2\0\14\67"+
    "\1\371\5\67\5\0\2\67\41\0\1\372\43\0\1\373"+
    "\64\0\1\374\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9306];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\10\11\0\5\1\1\11\4\1\1\0\1\1\2\0"+
    "\1\1\1\0\13\1\2\0\1\11\2\1\1\11\2\1"+
    "\1\11\1\1\1\11\1\1\1\0\1\1\3\0\1\1"+
    "\2\11\14\1\2\0\1\11\1\0\1\11\4\0\1\1"+
    "\5\0\1\11\2\0\1\1\2\11\1\0\23\1\1\0"+
    "\1\11\1\0\1\11\1\0\1\1\1\11\1\0\1\11"+
    "\2\0\1\11\1\0\1\11\1\0\22\1\3\0\1\11"+
    "\1\0\1\11\2\0\24\1\1\11\2\0\1\11\2\0"+
    "\17\1\4\0\15\1\1\11\2\0\11\1\2\0\5\1"+
    "\2\0\4\1\2\0\4\1\2\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[252];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF = false;

  /* user code: */
    private ByteStack stack = new ByteStack();
    private LexerInput input;
    private int parenBalanceInDirective = 0; //for directive arguments
    private int parameterExpressionLength = 0;
    private int pushBackCount = 0;
    //[\"][^\:\"]+[\:]{1}[^\:]
    private Pattern freezePhpPattern = Pattern.compile("[^\\:\\\"\\)\\? ]+([\\:]{1}|[\\:]{3,})[^\\:]", Pattern.CASE_INSENSITIVE);

    public BladeColoringLexer(LexerRestartInfo<? extends TokenId> info) {
        this.input = info.input();
        if(info.state() != null) {
            //reset state
            setState((LexerState) info.state(), parenBalanceInDirective);
        } else {
            //initial state
            stack.push(ST_HTML);
            zzState = ST_HTML;
            zzLexicalState = ST_HTML;
        }

    }

    public static final class LexerState  {
        final ByteStack stack;
        /** the current state of the DFA */
        final int zzState;
        /** the current lexical state */
        final int zzLexicalState;
        final int parenBalanceInDirective; 

        LexerState(ByteStack stack, int zzState, int zzLexicalState, int parenBalanceInDirective) {
            this.stack = stack;
            this.zzState = zzState;
            this.zzLexicalState = zzLexicalState;
            this.parenBalanceInDirective = parenBalanceInDirective;
        }

        @Override
        public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (obj == null || obj.getClass() != this.getClass()) {
                return false;
            }
            LexerState state = (LexerState) obj;
            return (this.stack.equals(state.stack)
                && (this.zzState == state.zzState)
                );
        }

        @Override
        public int hashCode() {
            int hash = 11;
            hash = 31 * hash + this.zzState;
            hash = 31 * hash + this.zzLexicalState;
            hash = 31 * hash + this.parenBalanceInDirective;
            if (stack != null) {
                hash = 31 * hash + this.stack.hashCode();
            }
            return hash;
        }
    }

    public LexerState getState() {
        return new LexerState(stack.copyOf(), zzState, zzLexicalState, parenBalanceInDirective);
    }

    public void setState(LexerState state, int parenBalanceInDirective) {
        this.stack.copyFrom(state.stack);
        this.zzState = state.zzState;
        this.zzLexicalState = state.zzLexicalState;
        this.parenBalanceInDirective = state.parenBalanceInDirective;
    }

    protected int getZZLexicalState() {
        return zzLexicalState;
    }

    //other functions

    protected void pushBack(int i) {
        yypushback(i);
    }

    protected void popState() {
        yybegin(stack.pop());
    }

    protected void pushState(final int state) {
        stack.push(getZZLexicalState());
        yybegin(state);
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public BladeColoringLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public BladeColoringLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1800) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return input.readText().toString();
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
     return input.readText().charAt(pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return input.readLength();
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    input.backup(number);
    //zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public BladeTokenId findNextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    //int zzCurrentPosL;
    //int zzMarkedPosL;
    //int zzEndReadL = zzEndRead;
    //char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      //zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      //zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
      int tokenLength = 0;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
            zzInput = input.read();
            
            if(zzInput == LexerInput.EOF) {
                //end of input reached
                zzInput = YYEOF;
                break zzForAction;
                //notice: currently LexerInput.EOF == YYEOF
            }

          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            tokenLength = input.readLength();
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      if(zzInput != YYEOF) {
         input.backup(input.readLength() - tokenLength);
      }

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 56: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
       return BladeTokenId.T_BLADE_HAS_SECTION;
          }
        case 60: break;
        case 3: 
          { String yytext = yytext();
	//whitespace
    return BladeTokenId.NEWLINE;
          }
        case 61: break;
        case 39: 
          { return BladeTokenId.T_BLADE_SHOW;
          }
        case 62: break;
        case 20: 
          { if (yylength() == 2){
	    popState(); 
		return BladeTokenId.T_CLOSE_PHP;
	}
	yypushback(2);
    return BladeTokenId.T_PHP_ECHO;
          }
        case 63: break;
        case 10: 
          { parenBalanceInDirective = 0;
   popState();
   return BladeTokenId.T_BLADE_RPAREN;
          }
        case 64: break;
        case 26: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_IF;
          }
        case 65: break;
        case 55: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_FOREACH;
          }
        case 66: break;
        case 7: 
          { if (yylength() > 0){
        yypushback(1);
    }
    popState();
          }
        case 67: break;
        case 33: 
          { pushState(ST_BLADE_PHP);
    return BladeTokenId.T_BLADE_PHP_OPEN;
          }
        case 68: break;
        case 12: 
          { String text = yytext();
    parameterExpressionLength+= yylength();
          }
        case 69: break;
        case 44: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_YIELD;
          }
        case 70: break;
        case 40: 
          { return BladeTokenId.T_BLADE_STOP;
          }
        case 71: break;
        case 19: 
          { if (yylength() == 2){
       popState();
       return BladeTokenId.T_CLOSE_PHP;
    }
    yypushback(2);
    return BladeTokenId.T_PHP;
          }
        case 72: break;
        case 9: 
          { pushState(ST_BLADE_PARAMETER_EXPRESSION);
   parenBalanceInDirective = 1;
   parameterExpressionLength = 0;
   return BladeTokenId.T_BLADE_LPAREN;
          }
        case 73: break;
        case 49: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_ELSEIF;
          }
        case 74: break;
        case 43: 
          { return BladeTokenId.T_BLADE_ENDIF;
          }
        case 75: break;
        case 28: 
          { if (yylength() == 2){
       popState();
       return BladeTokenId.T_CLOSE_PHP;
    }
    yypushback(2);
    return BladeTokenId.T_PHP_ECHO;
          }
        case 76: break;
        case 45: 
          { //css directives
    return BladeTokenId.T_HTML;
          }
        case 77: break;
        case 36: 
          { popState();
    return BladeTokenId.T_BLADE_CLOSE_COMMENT;
          }
        case 78: break;
        case 25: 
          { //escape expression
    return BladeTokenId.T_HTML;
          }
        case 79: break;
        case 17: 
          { //escape directive rule
    return BladeTokenId.T_HTML;
          }
        case 80: break;
        case 18: 
          { //email format
    return BladeTokenId.T_HTML;
          }
        case 81: break;
        case 35: 
          { String yytext = yytext();
    if (yylength() == 3){
    	popState();
    	return BladeTokenId.T_BLADE_CLOSE_ECHO;
    }
    yypushback(3);
    Matcher matcher = freezePhpPattern.matcher(yytext);
    if(matcher.find()) {
        if(yytext.trim().startsWith("'") || yytext.trim().startsWith("\"")){
            return BladeTokenId.T_PHP_STRING;
        }
        return BladeTokenId.T_HTML;
    }
    return BladeTokenId.T_BLADE_PHP_ECHO;
          }
        case 82: break;
        case 2: 
          { String yytext = yytext();
	//whitespace
    return BladeTokenId.WHITESPACE;
          }
        case 83: break;
        case 30: 
          { String yytext = yytext();
    popState();
    return BladeTokenId.T_BLADE_CLOSE_ECHO_ESCAPED;
          }
        case 84: break;
        case 50: 
          { return BladeTokenId.T_XML;
          }
        case 85: break;
        case 38: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_EACH;
          }
        case 86: break;
        case 34: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_FOR;
          }
        case 87: break;
        case 46: 
          { return BladeTokenId.T_BLADE_PARENT;
          }
        case 88: break;
        case 15: 
          { String yytext = yytext();
    pushState(ST_BLADE_ECHO);
    return BladeTokenId.T_BLADE_OPEN_ECHO;
          }
        case 89: break;
        case 47: 
          { return BladeTokenId.T_BLADE_ENDPHP;
          }
        case 90: break;
        case 51: 
          { String ttext = yytext();
    popState();
    if (yylength() == "@endphp".length()){
        return BladeTokenId.T_BLADE_ENDPHP;
    }
    
    yypushback("@endphp".length());
    return BladeTokenId.T_BLADE_PHP;
          }
        case 91: break;
        case 8: 
          { return BladeTokenId.WHITESPACE;
          }
        case 92: break;
        case 42: 
          { yypushback(4);
    return BladeTokenId.T_BLADE_COMMENT;
          }
        case 93: break;
        case 14: 
          { parenBalanceInDirective--;
   if (parenBalanceInDirective == 0) {
      yypushback(1);
      popState();
      return BladeTokenId.T_BLADE_PHP_EXPRESSION;
   }
          }
        case 94: break;
        case 32: 
          { pushState(ST_COMMENT);
    return BladeTokenId.T_BLADE_OPEN_COMMENT;
          }
        case 95: break;
        case 54: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
       return BladeTokenId.T_BLADE_SECTION;
          }
        case 96: break;
        case 52: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_EXTENDS;
          }
        case 97: break;
        case 24: 
          { String yytext = yytext();
    pushState(ST_BLADE_ECHO_ESCAPED);
    return BladeTokenId.T_BLADE_OPEN_ECHO_ESCAPED;
          }
        case 98: break;
        case 58: 
          { return BladeTokenId.T_BLADE_ENDFOREACH;
          }
        case 99: break;
        case 53: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
        return BladeTokenId.T_BLADE_INCLUDE;
          }
        case 100: break;
        case 11: 
          { parameterExpressionLength =0;
          }
        case 101: break;
        case 57: 
          { return BladeTokenId.T_BLADE_ENDSECTION;
          }
        case 102: break;
        case 27: 
          { pushState(ST_PHP_ECHO);
    return BladeTokenId.T_PHP_OPEN_ECHO;
          }
        case 103: break;
        case 31: 
          { //php lexer embedding freeze issue when you type / delete a double colon at the start of the script
    if (parameterExpressionLength == 0) {
        popState();
        popState();
        parameterExpressionLength = 0;
        return  BladeTokenId.T_HTML;
    }
          }
        case 104: break;
        case 41: 
          { pushState(ST_PHP);
    return BladeTokenId.T_OPEN_PHP_SCRIPT;
          }
        case 105: break;
        case 16: 
          { String ttext = yytext();
    pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
    return BladeTokenId.T_BLADE_DIRECTIVE;
          }
        case 106: break;
        case 23: 
          { //incomplete comment
    return BladeTokenId.T_HTML;
          }
        case 107: break;
        case 59: 
          { pushState(ST_LOOKING_FOR_PARAMETER_EXPRESSION);
       return BladeTokenId.T_BLADE_SECTION_MISSING;
          }
        case 108: break;
        case 21: 
          { String yytext = yytext();
    popState();
    return BladeTokenId.T_BLADE_CLOSE_ECHO;
          }
        case 109: break;
        case 5: 
          { //no break;
    parameterExpressionLength += yylength();
          }
        case 110: break;
        case 48: 
          { return BladeTokenId.T_BLADE_ENDFOR;
          }
        case 111: break;
        case 37: 
          { return BladeTokenId.T_BLADE_ELSE;
          }
        case 112: break;
        case 6: 
          { String yytext = yytext();
    popState();
    return BladeTokenId.T_HTML;
          }
        case 113: break;
        case 22: 
          { parenBalanceInDirective = 0;
   popState();
   return BladeTokenId.T_EMPTY_EXPRESSION;
          }
        case 114: break;
        case 29: 
          { String yytext = yytext();
    if (yylength() == 2){
    	popState();
    	return BladeTokenId.T_BLADE_CLOSE_ECHO;
    }
    yypushback(2);

    Matcher matcher = freezePhpPattern.matcher(yytext);
    if(matcher.find()) {
        if(yytext.trim().startsWith("'") || yytext.trim().startsWith("\"")){
            return BladeTokenId.T_PHP_STRING;
        }
        return BladeTokenId.T_HTML;
    }
    return BladeTokenId.T_BLADE_PHP_ECHO;
          }
        case 115: break;
        case 13: 
          { parenBalanceInDirective++;
          }
        case 116: break;
        case 4: 
          { //skipp
          }
        case 117: break;
        case 1: 
          { return  BladeTokenId.T_HTML;
          }
        case 118: break;
        default: 
          if (zzInput == YYEOF) 
            //zzAtEOF = true;
            switch (zzLexicalState) {
            case ST_PHP: {
              if (input.readLength() > 0) {
    input.backup(1);  // backup eof
    return BladeTokenId.T_PHP;
  }
  else {
      return null;
  }
            }
            case 253: break;
            case ST_COMMENT: {
              popState();
  if (yylength() > 0){
    return BladeTokenId.T_HTML;
  }
            }
            case 254: break;
            default:
              {         if(input.readLength() > 0) {
            String yytext = yytext();
            // backup eof
            input.backup(1);
            //and return the text as error token
             return BladeTokenId.T_HTML;
        } else {
            return null;
        }
 }
            }
          
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
