/* The following code was generated by JFlex 1.4.3 on 3/3/22, 8:04 AM */


package org.netbeans.modules.php.blade.editor.parsing;

import java_cup.runtime.*;
import org.netbeans.modules.php.blade.editor.BladeSyntax;
import org.netbeans.modules.php.editor.parser.PHPParseResult;
import org.netbeans.modules.php.blade.editor.common.ByteStack;
import org.openide.filesystems.FileObject;

@org.netbeans.api.annotations.common.SuppressWarnings({"SF_SWITCH_FALLTHROUGH", "URF_UNREAD_FIELD", "DLS_DEAD_LOCAL_STORE", "DM_DEFAULT_ENCODING", "EI_EXPOSE_REP2", "UUF_UNUSED_FIELD"})


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 3/3/22, 8:04 AM from the specification file
 * <tt>ASTBladeScanner.flex</tt>
 */
public class ASTBladeScanner implements Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int ST_BLADE_PARAMETER_EXPRESSION = 34;
  public static final int ST_PHP = 26;
  public static final int ST_DOCBLOCK = 14;
  public static final int ST_BLADE_ECHO = 30;
  public static final int ST_LOOKING_FOR_LABEL = 4;
  public static final int ST_HTML_COMMENT = 38;
  public static final int ST_PHP_LOOP_EXPRESSION = 16;
  public static final int ST_BLADE_ECHO_ESCAPED = 32;
  public static final int ST_COMMENT = 28;
  public static final int ST_BLADE_DIRECTIVE = 8;
  public static final int ST_LOOK_FOR_DIRECTIVE_ARGUMENTS = 36;
  public static final int ST_BLADE_INCLUDE_ARGS = 20;
  public static final int ST_LOOKING_FOR_INCLUDED_VARS = 6;
  public static final int ST_STRING_DBQUOTE = 10;
  public static final int ST_BLADE_PARAMETER = 22;
  public static final int ST_STRING_SQUOTE = 12;
  public static final int ST_LOOKING_FOR_PATH = 2;
  public static final int YYINITIAL = 0;
  public static final int ST_INLINE_PHP = 24;
  public static final int ST_PHP_CONDITION_EXPRESSION = 18;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6, 
     7,  7,  8,  8,  9,  9, 10, 10,  6,  6, 11, 11, 12, 12, 13, 13, 
    14, 14, 15, 15, 16, 16, 17, 17
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\7\1\5\1\0\1\7\1\4\22\0\1\7\1\16\1\45"+
    "\1\0\1\51\1\53\1\0\1\46\1\44\1\50\2\0\1\47\1\17"+
    "\1\3\1\12\12\1\1\0\1\6\1\52\1\56\1\54\1\55\1\20"+
    "\1\43\1\13\1\23\1\30\1\22\1\42\1\13\1\33\1\25\2\13"+
    "\1\32\1\13\1\27\1\26\1\35\1\13\1\37\1\21\1\24\1\41"+
    "\1\36\1\34\1\40\1\31\1\13\4\0\1\2\1\0\1\43\1\13"+
    "\1\23\1\30\1\22\1\42\1\13\1\33\1\25\2\13\1\32\1\13"+
    "\1\27\1\26\1\35\1\13\1\37\1\21\1\24\1\41\1\36\1\34"+
    "\1\40\1\31\1\13\1\14\1\0\1\15\1\0\53\10\1\10\12\10"+
    "\1\10\4\10\1\10\5\10\27\10\1\10\37\10\1\10\10\10\u01c2\10"+
    "\4\0\14\10\16\0\5\10\7\0\1\10\1\0\1\10\201\0\5\10"+
    "\1\0\2\10\2\0\4\10\1\0\1\10\6\0\1\10\1\0\3\10"+
    "\1\0\1\10\1\0\24\10\1\0\123\10\1\0\213\10\10\0\246\10"+
    "\1\0\46\10\2\0\1\10\6\0\51\10\107\0\33\10\4\0\4\10"+
    "\55\0\53\10\25\0\12\11\4\0\2\10\1\0\143\10\1\0\1\10"+
    "\17\0\2\10\7\0\2\10\12\11\3\10\2\0\1\10\20\0\1\10"+
    "\1\0\36\10\35\0\131\10\13\0\1\10\16\0\12\11\41\10\11\0"+
    "\2\10\4\0\1\10\5\0\26\10\4\0\1\10\11\0\1\10\3\0"+
    "\1\10\27\0\31\10\7\0\13\10\65\0\25\10\1\0\22\10\74\0"+
    "\66\10\3\0\1\10\22\0\1\10\7\0\12\10\4\0\12\11\1\0"+
    "\20\10\4\0\10\10\2\0\2\10\2\0\26\10\1\0\7\10\1\0"+
    "\1\10\3\0\4\10\3\0\1\10\20\0\1\10\15\0\2\10\1\0"+
    "\3\10\4\0\12\11\2\10\12\0\1\10\10\0\6\10\4\0\2\10"+
    "\2\0\26\10\1\0\7\10\1\0\2\10\1\0\2\10\1\0\2\10"+
    "\37\0\4\10\1\0\1\10\7\0\12\11\2\0\3\10\20\0\11\10"+
    "\1\0\3\10\1\0\26\10\1\0\7\10\1\0\2\10\1\0\5\10"+
    "\3\0\1\10\22\0\1\10\17\0\2\10\4\0\12\11\11\0\1\10"+
    "\13\0\10\10\2\0\2\10\2\0\26\10\1\0\7\10\1\0\2\10"+
    "\1\0\5\10\3\0\1\10\36\0\2\10\1\0\3\10\4\0\12\11"+
    "\1\0\1\10\21\0\1\10\1\0\6\10\3\0\3\10\1\0\4\10"+
    "\3\0\2\10\1\0\1\10\1\0\2\10\3\0\2\10\3\0\3\10"+
    "\3\0\14\10\26\0\1\10\25\0\12\11\25\0\10\10\1\0\3\10"+
    "\1\0\27\10\1\0\20\10\3\0\1\10\32\0\3\10\5\0\2\10"+
    "\4\0\12\11\20\0\1\10\4\0\10\10\1\0\3\10\1\0\27\10"+
    "\1\0\12\10\1\0\5\10\3\0\1\10\40\0\1\10\1\0\2\10"+
    "\4\0\12\11\1\0\2\10\21\0\11\10\1\0\3\10\1\0\51\10"+
    "\2\0\1\10\20\0\1\10\5\0\3\10\10\0\3\10\4\0\12\11"+
    "\12\0\6\10\5\0\22\10\3\0\30\10\1\0\11\10\1\0\1\10"+
    "\2\0\7\10\37\0\12\11\21\0\60\10\1\0\2\10\14\0\7\10"+
    "\11\0\12\11\47\0\2\10\1\0\1\10\1\0\5\10\1\0\30\10"+
    "\1\0\1\10\1\0\12\10\1\0\2\10\11\0\1\10\2\0\5\10"+
    "\1\0\1\10\11\0\12\11\2\0\4\10\40\0\1\10\37\0\12\11"+
    "\26\0\10\10\1\0\44\10\33\0\5\10\163\0\53\10\24\0\1\10"+
    "\12\11\6\0\6\10\4\0\4\10\3\0\1\10\3\0\2\10\7\0"+
    "\3\10\4\0\15\10\14\0\1\10\1\0\12\11\6\0\46\10\1\0"+
    "\1\10\5\0\1\10\2\0\53\10\1\0\u014d\10\1\0\4\10\2\0"+
    "\7\10\1\0\1\10\1\0\4\10\2\0\51\10\1\0\4\10\2\0"+
    "\41\10\1\0\4\10\2\0\7\10\1\0\1\10\1\0\4\10\2\0"+
    "\17\10\1\0\71\10\1\0\4\10\2\0\103\10\45\0\20\10\20\0"+
    "\126\10\2\0\6\10\3\0\u026c\10\2\0\21\10\1\0\32\10\5\0"+
    "\113\10\6\0\10\10\7\0\15\10\1\0\4\10\16\0\22\10\16\0"+
    "\22\10\16\0\15\10\1\0\3\10\17\0\64\10\43\0\1\10\4\0"+
    "\1\10\3\0\12\11\46\0\12\11\6\0\131\10\7\0\5\10\2\0"+
    "\42\10\1\0\1\10\5\0\106\10\12\0\37\10\47\0\12\11\36\10"+
    "\2\0\5\10\13\0\54\10\4\0\32\10\6\0\12\11\46\0\27\10"+
    "\11\0\65\10\53\0\12\11\6\0\12\11\15\0\1\10\135\0\57\10"+
    "\21\0\7\10\4\0\12\11\51\0\36\10\15\0\2\10\12\11\54\10"+
    "\32\0\44\10\34\0\12\11\3\0\3\10\12\11\44\10\2\0\11\10"+
    "\7\0\53\10\2\0\3\10\51\0\4\10\1\0\6\10\1\0\2\10"+
    "\3\0\1\10\5\0\300\10\100\0\u0116\10\2\0\6\10\2\0\46\10"+
    "\2\0\6\10\2\0\10\10\1\0\1\10\1\0\1\10\1\0\1\10"+
    "\1\0\37\10\2\0\65\10\1\0\7\10\1\0\1\10\3\0\3\10"+
    "\1\0\7\10\3\0\4\10\2\0\6\10\4\0\15\10\5\0\3\10"+
    "\1\0\7\10\164\0\1\10\15\0\1\10\20\0\15\10\145\0\1\10"+
    "\4\0\1\10\2\0\12\10\1\0\1\10\3\0\5\10\6\0\1\10"+
    "\1\0\1\10\1\0\1\10\1\0\4\10\1\0\13\10\2\0\4\10"+
    "\5\0\5\10\4\0\1\10\64\0\2\10\u0a7b\0\57\10\1\0\57\10"+
    "\1\0\205\10\6\0\4\10\3\0\2\10\14\0\46\10\1\0\1\10"+
    "\5\0\1\10\2\0\70\10\7\0\1\10\20\0\27\10\11\0\7\10"+
    "\1\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10"+
    "\1\0\7\10\1\0\7\10\120\0\1\10\u01d5\0\2\10\52\0\5\10"+
    "\5\0\2\10\4\0\126\10\6\0\3\10\1\0\132\10\1\0\4\10"+
    "\5\0\53\10\1\0\136\10\21\0\40\10\60\0\20\10\u0200\0\u19c0\10"+
    "\100\0\u51fd\10\3\0\u048d\10\103\0\56\10\2\0\u010d\10\3\0\20\10"+
    "\12\11\2\10\24\0\57\10\20\0\37\10\2\0\106\10\61\0\11\10"+
    "\2\0\147\10\2\0\65\10\2\0\11\10\52\0\15\10\1\0\3\10"+
    "\1\0\4\10\1\0\27\10\35\0\64\10\16\0\62\10\34\0\12\11"+
    "\30\0\6\10\3\0\1\10\1\0\2\10\1\0\12\11\34\10\12\0"+
    "\27\10\31\0\35\10\7\0\57\10\34\0\1\10\12\11\6\0\5\10"+
    "\1\0\12\10\12\11\5\10\1\0\51\10\27\0\3\10\1\0\10\10"+
    "\4\0\12\11\6\0\27\10\3\0\1\10\3\0\62\10\1\0\1\10"+
    "\3\0\2\10\2\0\5\10\2\0\1\10\1\0\1\10\30\0\3\10"+
    "\2\0\13\10\7\0\3\10\14\0\6\10\2\0\6\10\2\0\6\10"+
    "\11\0\7\10\1\0\7\10\1\0\53\10\1\0\16\10\6\0\163\10"+
    "\15\0\12\11\6\0\u2ba4\10\14\0\27\10\4\0\61\10\u2104\0\u016e\10"+
    "\2\0\152\10\46\0\7\10\14\0\5\10\5\0\1\10\1\0\12\10"+
    "\1\0\15\10\1\0\5\10\1\0\1\10\1\0\2\10\1\0\2\10"+
    "\1\0\154\10\41\0\u016b\10\22\0\100\10\2\0\66\10\50\0\14\10"+
    "\164\0\5\10\1\0\207\10\23\0\12\11\7\0\32\10\6\0\32\10"+
    "\13\0\131\10\3\0\6\10\2\0\6\10\2\0\6\10\2\0\3\10"+
    "\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\22\0\1\1\2\2\1\3\1\1\2\4\2\5\1\4"+
    "\1\6\1\7\1\10\1\11\1\4\1\12\2\13\1\12"+
    "\1\2\1\4\2\2\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\4\2\1\26\2\27"+
    "\3\26\2\27\2\26\1\30\1\31\2\32\1\33\2\32"+
    "\1\0\1\34\3\0\1\5\2\35\1\5\1\36\1\37"+
    "\1\0\7\37\2\40\1\0\1\41\3\0\1\42\5\0"+
    "\2\26\1\43\2\0\2\26\6\0\1\44\2\0\1\45"+
    "\1\0\2\36\10\37\1\46\4\37\1\47\1\0\1\50"+
    "\1\26\1\50\1\0\1\26\1\43\1\51\1\52\1\53"+
    "\1\0\13\37\1\54\1\55\1\56\1\57\1\37\1\60"+
    "\1\61\4\37\1\62\4\37\1\0\5\37\1\63\5\37"+
    "\1\64\1\0\2\37\1\65\2\37\1\66\1\67\3\37"+
    "\1\0\1\37\1\70\3\37\1\71\1\72\1\37\1\0"+
    "\1\73\5\37\1\0\1\37\1\74\1\37\1\72\1\75"+
    "\1\0\1\76\1\77\1\0\1\100";

  private static int [] zzUnpackAction() {
    int [] result = new int[227];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1"+
    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u011a\0\u011a\0\u03ac\0\u03db"+
    "\0\u040a\0\u0439\0\u0468\0\u0497\0\u011a\0\u011a\0\u011a\0\u011a"+
    "\0\u04c6\0\u04f5\0\u0524\0\u0468\0\u0553\0\u0582\0\u05b1\0\u05e0"+
    "\0\u060f\0\u011a\0\u011a\0\u011a\0\u011a\0\u011a\0\u011a\0\u011a"+
    "\0\u011a\0\u011a\0\u011a\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0814"+
    "\0\u0843\0\u011a\0\u011a\0\u0872\0\u011a\0\u011a\0\u08a1\0\u08d0"+
    "\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u0a48"+
    "\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0"+
    "\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u05e0\0\u011a\0\u060f"+
    "\0\u063e\0\u0cda\0\u011a\0\u069c\0\u06cb\0\u0d09\0\u06fa\0\u0d38"+
    "\0\u0d67\0\u0d96\0\u0dc5\0\u07b6\0\u0df4\0\u0e23\0\u0e52\0\u0e81"+
    "\0\u0eb0\0\u08a1\0\u08d0\0\u0edf\0\u0f0e\0\u011a\0\u0f3d\0\u0f6c"+
    "\0\u011a\0\u0f9b\0\u0b04\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\u1086"+
    "\0\u10b5\0\u10e4\0\u1113\0\u1142\0\u0ad5\0\u1171\0\u11a0\0\u11cf"+
    "\0\u11fe\0\u011a\0\u122d\0\u0dc5\0\u125c\0\u011a\0\u128b\0\u12ba"+
    "\0\u011a\0\u011a\0\u011a\0\u011a\0\u12e9\0\u1318\0\u1347\0\u1376"+
    "\0\u13a5\0\u13d4\0\u1403\0\u1432\0\u1461\0\u1490\0\u14bf\0\u14ee"+
    "\0\u151d\0\u011a\0\u011a\0\u011a\0\u154c\0\u0ad5\0\u0ad5\0\u157b"+
    "\0\u15aa\0\u15d9\0\u1608\0\u1637\0\u1666\0\u1695\0\u16c4\0\u16f3"+
    "\0\u1722\0\u1751\0\u1780\0\u17af\0\u17de\0\u180d\0\u0ad5\0\u183c"+
    "\0\u186b\0\u189a\0\u18c9\0\u18f8\0\u0ad5\0\u1927\0\u1956\0\u1985"+
    "\0\u0ad5\0\u19b4\0\u19e3\0\u1a12\0\u0ad5\0\u1a41\0\u1a70\0\u1a9f"+
    "\0\u1ace\0\u1afd\0\u0ad5\0\u1b2c\0\u1b5b\0\u1b8a\0\u0ad5\0\u1bb9"+
    "\0\u1be8\0\u1c17\0\u0ad5\0\u1c46\0\u1c75\0\u1ca4\0\u1cd3\0\u1d02"+
    "\0\u1d31\0\u1d60\0\u0ad5\0\u1d8f\0\u0ad5\0\u0ad5\0\u1dbe\0\u0ad5"+
    "\0\u0ad5\0\u1ded\0\u011a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[227];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\14\23\1\24\1\25\2\23\1\26\31\23\1\27\4\23"+
    "\1\0\1\30\1\31\1\30\1\32\1\33\1\0\1\33"+
    "\1\34\1\0\1\30\1\31\3\0\1\30\1\0\23\31"+
    "\1\35\1\36\1\37\1\0\1\40\1\41\5\0\1\25"+
    "\1\30\1\31\1\30\1\32\1\33\1\25\1\33\1\34"+
    "\1\25\1\30\1\31\3\25\1\30\1\25\23\31\1\35"+
    "\1\36\1\37\1\25\1\40\1\41\6\25\1\30\1\42"+
    "\1\30\1\43\1\44\1\25\1\33\1\45\1\25\1\30"+
    "\1\42\3\25\1\30\1\46\23\42\1\35\1\36\1\37"+
    "\1\25\1\40\1\47\52\25\1\50\57\25\1\51\10\25"+
    "\57\0\4\52\1\32\1\33\1\52\1\33\34\52\1\53"+
    "\3\52\1\54\12\52\1\32\1\33\1\52\1\33\34\52"+
    "\1\53\3\52\1\55\6\52\44\56\1\57\1\36\1\37"+
    "\1\60\1\61\52\56\1\62\3\56\1\63\6\56\55\64"+
    "\1\65\1\64\17\66\1\67\37\66\4\70\1\71\1\72"+
    "\1\70\1\73\5\70\1\74\41\70\4\75\1\76\1\77"+
    "\1\75\1\100\6\75\1\101\40\75\4\52\1\32\1\33"+
    "\1\52\1\33\34\52\1\53\3\52\1\102\6\52\4\103"+
    "\1\104\1\105\1\103\1\105\34\103\1\106\12\103\17\107"+
    "\1\110\37\107\14\23\2\0\2\23\1\0\31\23\1\111"+
    "\4\23\14\0\1\112\1\0\1\113\40\0\16\23\1\114"+
    "\33\23\2\0\1\23\1\115\1\23\1\0\3\30\6\0"+
    "\2\30\3\0\1\30\1\0\23\30\5\0\1\30\6\0"+
    "\2\31\1\30\4\0\2\34\1\30\1\31\3\0\1\30"+
    "\1\0\23\31\5\0\1\30\11\0\1\32\1\116\1\0"+
    "\1\33\53\0\1\32\1\33\1\0\1\33\50\0\2\34"+
    "\5\0\2\34\1\0\1\34\5\0\23\34\14\0\1\30"+
    "\1\117\1\30\4\0\1\120\1\0\1\30\1\117\3\0"+
    "\1\30\1\0\23\117\5\0\1\30\6\0\2\42\1\30"+
    "\4\0\2\45\1\30\1\42\3\0\1\30\1\0\23\42"+
    "\5\0\1\30\11\0\1\32\1\121\1\0\1\33\50\0"+
    "\2\45\5\0\2\45\1\0\1\45\5\0\23\45\14\0"+
    "\1\122\1\123\1\124\4\0\1\123\2\0\1\123\5\0"+
    "\1\125\1\126\2\123\1\127\1\130\2\123\1\131\3\123"+
    "\1\132\4\123\1\133\1\123\14\0\1\30\1\134\1\30"+
    "\4\0\1\135\1\0\1\30\1\134\3\0\1\30\1\0"+
    "\23\134\5\0\1\30\5\0\45\136\1\137\11\136\46\140"+
    "\1\137\10\140\55\141\1\142\55\141\1\143\1\142\1\141"+
    "\17\144\1\145\56\144\1\146\37\144\15\147\1\150\45\147"+
    "\1\151\1\152\1\147\1\73\5\147\1\150\45\147\1\151"+
    "\1\73\1\147\1\73\5\147\1\150\56\147\1\153\41\147"+
    "\16\154\1\155\44\154\1\156\1\157\1\154\1\100\6\154"+
    "\1\155\44\154\1\156\1\100\1\154\1\100\6\154\1\155"+
    "\56\154\1\160\40\154\5\0\1\161\51\0\17\162\1\163"+
    "\56\162\1\164\37\162\16\23\1\0\33\23\2\0\1\23"+
    "\1\0\1\23\17\0\1\165\55\0\1\166\57\0\1\167"+
    "\74\0\1\170\20\0\1\171\4\0\1\32\3\33\50\0"+
    "\2\117\1\30\4\0\2\120\1\30\1\117\3\0\1\30"+
    "\1\0\23\117\5\0\1\30\6\0\2\120\5\0\2\120"+
    "\1\0\1\120\5\0\23\120\17\0\1\32\1\33\1\44"+
    "\1\33\50\0\1\122\1\172\1\173\54\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\23\123\14\0\1\174\56\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\1\123\1\175"+
    "\1\123\1\176\6\123\1\177\1\200\7\123\14\0\2\123"+
    "\5\0\2\123\1\0\1\123\5\0\6\123\1\201\2\123"+
    "\1\202\5\123\1\203\3\123\14\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\6\123\1\204\12\123\1\205\1\123"+
    "\14\0\2\123\5\0\2\123\1\0\1\123\5\0\15\123"+
    "\1\206\5\123\14\0\2\123\5\0\2\123\1\0\1\123"+
    "\5\0\4\123\1\207\16\123\14\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\12\123\1\210\10\123\14\0\2\123"+
    "\5\0\2\123\1\0\1\123\5\0\5\123\1\211\15\123"+
    "\14\0\2\134\1\30\4\0\2\135\1\30\1\134\3\0"+
    "\1\30\1\0\23\134\5\0\1\30\6\0\2\135\5\0"+
    "\2\135\1\0\1\135\5\0\23\135\13\0\54\141\1\212"+
    "\1\142\1\141\15\144\1\213\1\144\1\146\37\144\15\147"+
    "\1\214\45\147\1\151\1\215\1\147\1\73\5\147\1\150"+
    "\45\147\1\151\1\73\1\72\1\73\5\147\1\150\41\147"+
    "\15\0\1\216\41\0\16\154\1\217\44\154\1\156\1\220"+
    "\1\154\1\100\6\154\1\155\44\154\1\156\1\100\1\77"+
    "\1\100\6\154\1\155\55\154\1\221\1\217\40\154\6\0"+
    "\1\105\50\0\17\162\1\164\34\162\1\222\2\162\17\0"+
    "\1\223\56\0\1\224\72\0\1\225\24\0\1\122\56\0"+
    "\1\174\1\124\55\0\2\123\5\0\2\123\1\0\1\123"+
    "\5\0\2\123\1\226\20\123\14\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\5\123\1\227\15\123\14\0\2\123"+
    "\5\0\2\123\1\0\1\123\5\0\5\123\1\230\15\123"+
    "\14\0\2\123\5\0\2\123\1\0\1\123\5\0\4\123"+
    "\1\231\16\123\14\0\2\123\5\0\2\123\1\0\1\123"+
    "\5\0\7\123\1\232\13\123\14\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\1\233\22\123\14\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\3\123\1\234\17\123\14\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\2\123\1\235"+
    "\20\123\14\0\2\123\5\0\2\123\1\0\1\123\5\0"+
    "\1\123\1\236\21\123\14\0\2\123\5\0\2\123\1\0"+
    "\1\123\5\0\1\123\1\237\21\123\14\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\14\123\1\240\6\123\14\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\16\123\1\241"+
    "\4\123\13\0\15\144\1\242\1\144\1\145\37\144\4\147"+
    "\1\151\3\73\5\147\1\150\41\147\15\154\1\243\1\217"+
    "\44\154\1\156\3\100\6\154\1\155\40\154\35\0\1\244"+
    "\22\0\2\123\5\0\2\123\1\0\1\123\5\0\3\123"+
    "\1\245\17\123\14\0\2\123\5\0\2\123\1\0\1\123"+
    "\5\0\14\123\1\246\6\123\14\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\13\123\1\247\7\123\14\0\2\123"+
    "\5\0\2\123\1\0\1\123\5\0\3\123\1\250\17\123"+
    "\14\0\2\123\5\0\2\123\1\0\1\123\5\0\1\251"+
    "\3\123\1\252\14\123\1\253\1\123\14\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\1\123\1\254\21\123\14\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\1\123\1\255"+
    "\21\123\14\0\2\123\5\0\2\123\1\0\1\123\5\0"+
    "\11\123\1\256\11\123\14\0\2\123\5\0\2\123\1\0"+
    "\1\123\5\0\16\123\1\257\4\123\14\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\11\123\1\260\11\123\14\0"+
    "\2\123\1\0\2\261\1\0\1\261\2\123\1\0\1\123"+
    "\5\0\23\123\14\0\2\123\5\0\2\123\1\0\1\123"+
    "\5\0\1\123\1\262\21\123\14\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\4\123\1\263\16\123\14\0\2\123"+
    "\5\0\2\123\1\0\1\123\5\0\2\123\1\264\20\123"+
    "\14\0\2\123\5\0\2\123\1\0\1\123\5\0\1\123"+
    "\1\265\11\123\1\266\7\123\14\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\21\123\1\267\1\123\14\0\2\123"+
    "\5\0\2\123\1\0\1\123\5\0\5\123\1\270\15\123"+
    "\14\0\2\123\5\0\2\123\1\0\1\123\5\0\4\123"+
    "\1\271\16\123\14\0\2\123\5\0\2\123\1\0\1\123"+
    "\5\0\6\123\1\272\14\123\14\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\20\123\1\273\2\123\14\0\2\123"+
    "\5\0\2\123\1\0\1\123\5\0\13\123\1\274\7\123"+
    "\14\0\2\123\5\0\2\123\1\0\1\123\5\0\7\123"+
    "\1\275\13\123\13\0\20\261\1\276\36\261\1\0\2\123"+
    "\5\0\2\123\1\0\1\123\5\0\22\123\1\277\14\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\5\123\1\300"+
    "\15\123\14\0\2\123\5\0\2\123\1\0\1\123\5\0"+
    "\12\123\1\301\10\123\14\0\2\123\5\0\2\123\1\0"+
    "\1\123\5\0\2\123\1\302\20\123\14\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\4\123\1\303\16\123\14\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\16\123\1\304"+
    "\4\123\14\0\2\123\5\0\2\123\1\0\1\123\5\0"+
    "\21\123\1\305\1\123\14\0\2\123\5\0\2\123\1\0"+
    "\1\123\5\0\7\123\1\306\13\123\14\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\7\123\1\307\13\123\14\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\16\123\1\310"+
    "\4\123\13\0\20\261\1\276\1\261\1\311\34\261\1\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\2\123\1\312"+
    "\20\123\14\0\2\123\5\0\2\123\1\0\1\123\5\0"+
    "\6\123\1\313\14\123\14\0\2\123\5\0\2\123\1\0"+
    "\1\123\5\0\3\123\1\314\17\123\14\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\3\123\1\315\17\123\14\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\1\123\1\316"+
    "\21\123\14\0\2\123\5\0\2\123\1\0\1\123\5\0"+
    "\1\317\22\123\14\0\2\123\5\0\2\123\1\0\1\123"+
    "\5\0\1\123\1\320\21\123\14\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\4\123\1\321\16\123\13\0\20\261"+
    "\1\276\6\261\1\322\27\261\1\0\2\123\5\0\2\123"+
    "\1\0\1\123\5\0\12\123\1\323\10\123\14\0\2\123"+
    "\5\0\2\123\1\0\1\123\5\0\4\123\1\324\16\123"+
    "\14\0\2\123\5\0\2\123\1\0\1\123\5\0\2\123"+
    "\1\325\20\123\14\0\2\123\5\0\2\123\1\0\1\123"+
    "\5\0\22\123\1\326\14\0\2\123\5\0\2\123\1\0"+
    "\1\123\5\0\4\123\1\327\16\123\14\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\3\123\1\330\17\123\13\0"+
    "\20\261\1\276\7\261\1\331\26\261\1\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\5\123\1\332\15\123\14\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\12\123\1\333"+
    "\10\123\14\0\2\123\5\0\2\123\1\0\1\123\5\0"+
    "\2\123\1\334\20\123\14\0\2\123\5\0\2\123\1\0"+
    "\1\123\5\0\21\123\1\335\1\123\14\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\1\123\1\336\21\123\13\0"+
    "\20\261\1\276\14\261\1\337\21\261\1\0\2\123\5\0"+
    "\2\123\1\0\1\123\5\0\6\123\1\340\14\123\14\0"+
    "\2\123\5\0\2\123\1\0\1\123\5\0\12\123\1\341"+
    "\10\123\13\0\20\261\1\276\12\261\1\342\43\261\1\276"+
    "\14\261\1\343\21\261";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7708];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\10\13\0\2\1\2\11\6\1\4\11\11\1"+
    "\12\11\16\1\2\11\1\1\2\11\2\1\1\0\1\1"+
    "\3\0\6\1\1\0\11\1\1\0\1\11\3\0\1\11"+
    "\5\0\3\1\2\0\2\1\6\0\1\11\2\0\1\11"+
    "\1\0\17\1\1\11\1\0\2\1\1\11\1\0\1\1"+
    "\4\11\1\0\14\1\3\11\14\1\1\0\14\1\1\0"+
    "\12\1\1\0\10\1\1\0\6\1\1\0\5\1\1\0"+
    "\2\1\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[227];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
    private ByteStack stack = new ByteStack();
    private char yy_old_buffer[] = new char[ZZ_BUFFERSIZE];
    private int yy_old_pushbackPos;
    private int whitespaceEndPosition;
    private int directiveParBalance = 0;
    private String phpConditionText = "";
    private String phpParameterExpressionText = "";
    private FileObject currentFile;
    private String fakePhpEmbeddingText = "";
    private int lastEmbeddedPos = -1;

    public void reset(java.io.Reader reader) {
        yyreset(reader);
    }

    public void setState(int state) {
        yybegin(state);
    }

    public int getState() {
        return yystate();
    }

    private void pushState(int state) {
        stack.push(zzLexicalState);
        yybegin(state);
    }

    private void popState() {
        yybegin(stack.pop());
    }

    public int getCurrentLine() {
        return yyline;
    }

    protected int getTokenStartPosition() {
        return zzStartRead - zzPushbackPos;
    }

    protected int getTokenLength() {
        return zzMarkedPos - zzStartRead;
    }

    public int getLength() {
        return zzEndRead - zzPushbackPos;
    }

    private Symbol createFullSymbol(int symbolNumber) {
        Symbol symbol = createSymbol(symbolNumber);
        symbol.value = yytext();
        return symbol;
    }

    private Symbol createConditionSymbol(int symbolNumber) {
        Symbol symbol = createSymbol(symbolNumber);
        symbol.value = phpConditionText;
        phpConditionText = "";
        return symbol;
    }


    private Symbol createPhpParameterExpression(int symbolNumber) {
        Symbol symbol = createSymbol(symbolNumber);
        symbol.value = phpParameterExpressionText;
        phpParameterExpressionText = "";
        return symbol;
    }


    private Symbol createSymbol(int symbolNumber) {
        int leftPosition = getTokenStartPosition();
        Symbol symbol = new Symbol(symbolNumber, leftPosition, leftPosition + getTokenLength());
        return symbol;
    }

    public int getWhitespaceEndPosition() {
        return whitespaceEndPosition;
    }

    private void error(String message) {
        System.out.println("Error at line " + (yyline + 1) + ", column " + (yycolumn + 1) + " : " + message);
    }

    protected void addBladePhpInline() {
        //TODO may think of an include with php
        //we will have to think of the offset
        int start = getTokenStartPosition();
        if (start > 1) {
            int offsetEmbed;
            if (lastEmbeddedPos < 0) {
                offsetEmbed = start - 2;
            } else {
                offsetEmbed = start - 2 - lastEmbeddedPos;
            }
            String emptyText = "";
            if (offsetEmbed > 0) {
                emptyText = new String(new char[offsetEmbed]).replace("\0", " ");
            }
            fakePhpEmbeddingText += emptyText + yytext().replace("@php", "<?php ").replace("@endphp", "    ?>");
        } else {
            String phpText = yytext().replace("@php", "<?  ").replace("@endphp", "////\n?>");
            if (phpText.length() == yytext().length()) {
                fakePhpEmbeddingText += phpText;
            }
        }

        lastEmbeddedPos = start + getTokenLength();
    }

    protected void addPhpStatement() {
        int start = getTokenStartPosition();
        int offsetEmbed;
        if (lastEmbeddedPos < 0) {
            offsetEmbed = start;
        } else {
            offsetEmbed = start - lastEmbeddedPos;
        }
        String emptyText = "";
        if (offsetEmbed > 0) {
            emptyText = new String(new char[offsetEmbed]).replace("\0", " ");
        }
        fakePhpEmbeddingText += emptyText + yytext();
        lastEmbeddedPos = start + getTokenLength();
    }
    
    protected void addEchoStatement(){
        int start = getTokenStartPosition();
        int offsetEmbed;
        //we assume that previous we had {{ or {!!
        if (lastEmbeddedPos < 0) {
            offsetEmbed = start - 3;
        } else {
            offsetEmbed = start - 3 - lastEmbeddedPos;
        }
        String emptyText;
        if (offsetEmbed > 0) {
            emptyText = new String(new char[offsetEmbed]).replace("\0", " ");
            fakePhpEmbeddingText += emptyText + "<?=" + yytext() + "?>";
            lastEmbeddedPos = start + getTokenLength() + 2;
        }
        
    }

    public String getFakePhpEmbeddingText() {
        return fakePhpEmbeddingText;
    }

    public void setCurentFile(FileObject file) {
        currentFile = file;
    }

    public PHPParseResult getPhpParserResult() {
        ParsingUtils parsingUtils = new ParsingUtils();
        if (fakePhpEmbeddingText.length() > 0) {
            parsingUtils.parsePhpText(fakePhpEmbeddingText);
        } else {
            parsingUtils.parsePhpText("<?php\n");
        }

        return parsingUtils.getParserResult();
    }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ASTBladeScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ASTBladeScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1802) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
//    if (!zzEOFDone) {
//      zzEOFDone = true;
//      yyclose();
//    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 18: 
          { if (phpParameterExpressionText.trim().length() > 0){
            yypushback(1);
            return createPhpParameterExpression(ASTBladeSymbols.T_PHP_PARAMETER_EXPRESSION);
        }
        pushState(ST_BLADE_PARAMETER);
        return createSymbol(ASTBladeSymbols.T_COMMA);
          }
        case 65: break;
        case 15: 
          { directiveParBalance--;
    phpConditionText += yytext();
    if (directiveParBalance <= 0){
        directiveParBalance = 0;
  		 yybegin(YYINITIAL);
   		 return createConditionSymbol(ASTBladeSymbols.T_PHP_CONDITION_EXPRESSION);
    }
          }
        case 66: break;
        case 53: 
          { pushState(ST_LOOK_FOR_DIRECTIVE_ARGUMENTS);
    	return createFullSymbol(ASTBladeSymbols.T_BLADE_SWITCH);
          }
        case 67: break;
        case 62: 
          { popState();
    	return createFullSymbol(ASTBladeSymbols.T_BLADE_ENDSECTION);
          }
        case 68: break;
        case 28: 
          { String yytext = yytext();
    pushState(ST_BLADE_ECHO);
    return createFullSymbol(ASTBladeSymbols.T_BLADE_OPEN_ECHO);
          }
        case 69: break;
        case 61: 
          { popState();
        return createFullSymbol(ASTBladeSymbols.T_BLADE_OVERWRITE);
          }
        case 70: break;
        case 46: 
          { String yytext = yytext();
    yypushback(3);
    return createFullSymbol(ASTBladeSymbols.T_BLADE_PHP_ECHO);
          }
        case 71: break;
        case 4: 
          { return createFullSymbol(ASTBladeSymbols.T_STRING);
          }
        case 72: break;
        case 24: 
          { directiveParBalance--;
    phpConditionText += yytext();
    if (directiveParBalance <= 0){
        directiveParBalance = 0;
  		 yypushback(1);
         popState();
   		 return createConditionSymbol(ASTBladeSymbols.T_PHP_PARAMETER_EXPRESSION);
    }
          }
        case 73: break;
        case 59: 
          { pushState(ST_PHP_LOOP_EXPRESSION);
        return createFullSymbol(ASTBladeSymbols.T_BLADE_FOREACH);
          }
        case 74: break;
        case 50: 
          { //pop the state
        popState();
        return createFullSymbol(ASTBladeSymbols.T_BLADE_DIRECTIVE);
          }
        case 75: break;
        case 2: 
          { // do nothing
          }
        case 76: break;
        case 34: 
          { //yypushback(2);
    popState();
    return createFullSymbol(ASTBladeSymbols.T_INLINE_PHP);
          }
        case 77: break;
        case 3: 
          { pushState(ST_BLADE_DIRECTIVE);
    if (yylength() > 0){
        yypushback(1);
        return createFullSymbol(ASTBladeSymbols.T_INLINE_HTML);
    }
          }
        case 78: break;
        case 17: 
          { directiveParBalance++;
        if (phpParameterExpressionText.trim().length() > 0){
            phpParameterExpressionText += yytext();
        }
    	return createSymbol(ASTBladeSymbols.T_OPEN_PARENTHESE);
          }
        case 79: break;
        case 55: 
          { pushState(ST_PHP_CONDITION_EXPRESSION);
        return createFullSymbol(ASTBladeSymbols.T_BLADE_ELSEIF);
          }
        case 80: break;
        case 38: 
          { pushState(ST_PHP_CONDITION_EXPRESSION);
        return createFullSymbol(ASTBladeSymbols.T_BLADE_IF);
          }
        case 81: break;
        case 21: 
          { String yytext = yytext();
    	directiveParBalance--;
    	if (directiveParBalance <= 0){
            directiveParBalance =0;
    		if (phpParameterExpressionText.length() > 0){
    			directiveParBalance++;
    			yypushback(1);
    			popState();
    			return createPhpParameterExpression(ASTBladeSymbols.T_PHP_PARAMETER_EXPRESSION);
    		} else {
    			yybegin(YYINITIAL);
            	return createSymbol(ASTBladeSymbols.T_CLOSE_PARENTHESE);
            }
    	}
          }
        case 82: break;
        case 19: 
          { String yytext = yytext();
    	directiveParBalance--;
    	if (directiveParBalance <= 0){
            directiveParBalance = 0;
            //exit out of ST_BLADE_INCLUDE_ARGS
            if (phpParameterExpressionText.trim().length() > 0){
                directiveParBalance++;
                yypushback(1);
                return createPhpParameterExpression(ASTBladeSymbols.T_PHP_PARAMETER_EXPRESSION);
            }
    		yybegin(YYINITIAL);
    		
    	}
    	return createSymbol(ASTBladeSymbols.T_CLOSE_PARENTHESE);
          }
        case 83: break;
        case 57: 
          { pushState(ST_BLADE_INCLUDE_ARGS);
    	return createFullSymbol(ASTBladeSymbols.T_BLADE_EXTENDS);
          }
        case 84: break;
        case 20: 
          { //skipping the parameter
    	directiveParBalance++;
    	//return createSymbol(ASTBladeSymbols.T_OPEN_PARENTHESE);
          }
        case 85: break;
        case 35: 
          { String yytext = yytext();
    popState();
    return createFullSymbol(ASTBladeSymbols.T_BLADE_CLOSE_ECHO);
          }
        case 86: break;
        case 58: 
          { pushState(ST_BLADE_INCLUDE_ARGS);
       return createFullSymbol(ASTBladeSymbols.T_BLADE_INCLUDE);
          }
        case 87: break;
        case 60: 
          { popState();
    	return createFullSymbol(ASTBladeSymbols.T_BLADE_ENDSWITCH);
          }
        case 88: break;
        case 25: 
          { yybegin(YYINITIAL);
   yypushback(1);
   return createFullSymbol(ASTBladeSymbols.T_INLINE_HTML);
          }
        case 89: break;
        case 12: 
          { String yytext = yytext();
	int debug = 1;
	phpConditionText += yytext();
          }
        case 90: break;
        case 49: 
          { popState();
        return createFullSymbol(ASTBladeSymbols.T_BLADE_SHOW);
          }
        case 91: break;
        case 30: 
          { String yytext = yytext();
    	popState();
    	return createFullSymbol(ASTBladeSymbols.T_INLINE_HTML);
          }
        case 92: break;
        case 63: 
          { popState();
        return createFullSymbol(ASTBladeSymbols.T_BLADE_ENDFOREACH);
          }
        case 93: break;
        case 64: 
          { popState();
        addBladePhpInline();
        return createFullSymbol(ASTBladeSymbols.T_BLADE_INLINE_PHP);
          }
        case 94: break;
        case 41: 
          { popState();
    return createFullSymbol(ASTBladeSymbols.T_INLINE_HTML);
          }
        case 95: break;
        case 39: 
          { //yypushback(2);
    addPhpStatement();
    popState();
    return createFullSymbol(ASTBladeSymbols.T_INLINE_PHP);
          }
        case 96: break;
        case 33: 
          { popState(); 
   return createFullSymbol(ASTBladeSymbols.T_STRING);
          }
        case 97: break;
        case 1: 
          { return createFullSymbol(ASTBladeSymbols.T_INLINE_HTML);
          }
        case 98: break;
        case 37: 
          { yypushback(3);
    pushState(ST_PHP);
          }
        case 99: break;
        case 5: 
          { whitespaceEndPosition = getTokenStartPosition() + yylength();
          }
        case 100: break;
        case 32: 
          { //to be refactored
        return createFullSymbol(ASTBladeSymbols.T_VARIABLE);
          }
        case 101: break;
        case 43: 
          { yypushback(4);
    pushState(ST_HTML_COMMENT);
    //return createFullSymbol(ASTBladeSymbols.T_INLINE_HTML);
          }
        case 102: break;
        case 16: 
          { phpParameterExpressionText += yytext();
          }
        case 103: break;
        case 8: 
          { yypushback(1);pushState(ST_STRING_SQUOTE);
          }
        case 104: break;
        case 36: 
          { String yytext = yytext();
    pushState(ST_BLADE_ECHO_ESCAPED);
    return createFullSymbol(ASTBladeSymbols.T_BLADE_OPEN_ECHO);
          }
        case 105: break;
        case 52: 
          { pushState(ST_BLADE_INCLUDE_ARGS);
	    return createFullSymbol(ASTBladeSymbols.T_BLADE_YIELD);
          }
        case 106: break;
        case 51: 
          { popState();
        return createFullSymbol(ASTBladeSymbols.T_BLADE_ENDIF);
          }
        case 107: break;
        case 45: 
          { popState();
    return createFullSymbol(ASTBladeSymbols.T_BLADE_COMMENT);
          }
        case 108: break;
        case 6: 
          { directiveParBalance++;
    	return createSymbol(ASTBladeSymbols.T_OPEN_PARENTHESE);
          }
        case 109: break;
        case 11: 
          { String yytext = yytext();
       popState();
       return createFullSymbol(ASTBladeSymbols.T_INLINE_HTML);
          }
        case 110: break;
        case 13: 
          { directiveParBalance++;
    phpConditionText += yytext();
          }
        case 111: break;
        case 44: 
          { pushState(ST_PHP_LOOP_EXPRESSION);
        return createFullSymbol(ASTBladeSymbols.T_BLADE_FOR);
          }
        case 112: break;
        case 7: 
          { yypushback(1);pushState(ST_STRING_DBQUOTE);
          }
        case 113: break;
        case 56: 
          { pushState(ST_BLADE_INCLUDE_ARGS);
        return createFullSymbol(ASTBladeSymbols.T_BLADE_SECTION);
          }
        case 114: break;
        case 54: 
          { popState();
        return createFullSymbol(ASTBladeSymbols.T_BLADE_ENDFOR);
          }
        case 115: break;
        case 23: 
          { String yytext = yytext();
    popState();
    return createFullSymbol(ASTBladeSymbols.T_INLINE_HTML);
          }
        case 116: break;
        case 47: 
          { yypushback(5);
    pushState(ST_PHP);
          }
        case 117: break;
        case 42: 
          { yypushback(4);
    pushState(ST_COMMENT);
          }
        case 118: break;
        case 9: 
          { directiveParBalance--;
    	if (directiveParBalance <= 0){
            directiveParBalance = 0;
    		yybegin(YYINITIAL);
    	}
    	return createSymbol(ASTBladeSymbols.T_CLOSE_PARENTHESE);
          }
        case 119: break;
        case 48: 
          { popState();
        return createFullSymbol(ASTBladeSymbols.T_BLADE_STOP);
          }
        case 120: break;
        case 27: 
          { //TO TEST
    //directiveParBalance++;
    popState();
    yypushback(1);
    pushState(ST_BLADE_PARAMETER_EXPRESSION);
    return createSymbol(ASTBladeSymbols.T_OPEN_PARENTHESE);
          }
        case 121: break;
        case 14: 
          { directiveParBalance--;
    phpConditionText += yytext();
    if (directiveParBalance <= 0){
        directiveParBalance = 0;
  		 yybegin(YYINITIAL);
   		 return createConditionSymbol(ASTBladeSymbols.T_PHP_LOOP_EXPRESSION);
    }
          }
        case 122: break;
        case 31: 
          { String yytext = yytext();
       if (BladeSyntax.CONDITIONAL_DIRECTIVES.contains(yytext)) {
             pushState(ST_PHP_CONDITION_EXPRESSION);
             return createFullSymbol(ASTBladeSymbols.T_BLADE_CONDITION_OPEN_TAG);
       }
       pushState(ST_LOOK_FOR_DIRECTIVE_ARGUMENTS);
       return createFullSymbol(ASTBladeSymbols.T_BLADE_DIRECTIVE);
          }
        case 123: break;
        case 40: 
          { String yytext = yytext();
    yypushback(2);
    return createFullSymbol(ASTBladeSymbols.T_BLADE_PHP_ECHO);
          }
        case 124: break;
        case 22: 
          { //no break;
          }
        case 125: break;
        case 10: 
          { //to be refactored
        return createFullSymbol(ASTBladeSymbols.T_STRING);
          }
        case 126: break;
        case 29: 
          { return createFullSymbol(ASTBladeSymbols.T_VARIABLE);
          }
        case 127: break;
        case 26: 
          { 
          }
        case 128: break;
        default: 
          if (zzInput == YYEOF && (zzStartRead == zzCurrentPos || zzLexicalState == ST_DOCBLOCK)) {
            zzAtEOF = true;
            zzDoEOF();
              {     return createSymbol(ASTBladeSymbols.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
