
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 03 20:55:12 EET 2023
//----------------------------------------------------

package org.netbeans.modules.php.blade.editor.parsing;

/** CUP generated interface containing symbol constants. */
public interface ASTBladeSymbols {
  /* terminals */
  public static final int T_PHP_PARAMETER_EXPRESSION = 36;
  public static final int T_BLADE_APPEND = 16;
  public static final int T_BLADE_ELSEIF = 27;
  public static final int T_INLINE_PHP = 3;
  public static final int T_BLADE_EXTENDS = 18;
  public static final int T_BLADE_ELSEIF_END = 28;
  public static final int T_BLADE_FOR = 23;
  public static final int T_BLADE_SECTION = 12;
  public static final int T_BLADE_ENDSECTION = 13;
  public static final int T_BLADE_ENDFOR = 24;
  public static final int T_PARAMETER_EXPRESSION = 11;
  public static final int T_NEKUDA = 40;
  public static final int T_BLADE_CONDITION_OPEN_TAG = 26;
  public static final int T_BLADE_SWITCH = 30;
  public static final int T_PHP_CONDITION_EXPRESSION = 35;
  public static final int T_BLADE_COMMENT = 5;
  public static final int T_BLADE_STOP = 14;
  public static final int T_BLADE_INCLUDE_FIRST = 9;
  public static final int EOF = 0;
  public static final int T_BLADE_OVERWRITE = 15;
  public static final int error = 1;
  public static final int T_BLADE_INCLUDE_CONDITIONAL = 10;
  public static final int T_BLADE_ENDIF = 29;
  public static final int T_COMMA = 39;
  public static final int T_BLADE_INLINE_PHP = 4;
  public static final int T_STRING = 37;
  public static final int T_VARIABLE = 38;
  public static final int T_BLADE_ENDSWITCH = 31;
  public static final int T_BLADE_PHP_ECHO = 34;
  public static final int T_BLADE_SHOW = 17;
  public static final int T_BLADE_INCLUDE = 8;
  public static final int T_BLADE_DIRECTIVE = 32;
  public static final int T_BLADE_CLOSE_ECHO = 7;
  public static final int T_BLADE_ENDFOREACH = 22;
  public static final int T_BLADE_EACH = 20;
  public static final int T_BLADE_FOREACH = 21;
  public static final int T_CLOSE_PARENTHESE = 42;
  public static final int T_INLINE_HTML = 2;
  public static final int T_BLADE_OPEN_ECHO = 6;
  public static final int T_OPEN_PARENTHESE = 41;
  public static final int T_PHP_LOOP_EXPRESSION = 33;
  public static final int T_BLADE_IF = 25;
  public static final int T_BLADE_YIELD = 19;
}

