
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 19 12:16:34 EEST 2022
//----------------------------------------------------

package org.netbeans.modules.php.blade.editor.parsing;

/** CUP generated class containing symbol constants. */
public class ASTBladeSymbols {
  /* terminals */
  public static final int T_PHP_PARAMETER_EXPRESSION = 31;
  public static final int T_BLADE_APPEND = 13;
  public static final int T_BLADE_ELSEIF = 23;
  public static final int T_INLINE_PHP = 3;
  public static final int T_BLADE_EXTENDS = 15;
  public static final int T_BLADE_FOR = 19;
  public static final int T_BLADE_SECTION = 9;
  public static final int T_BLADE_ENDSECTION = 10;
  public static final int T_BLADE_ENDFOR = 20;
  public static final int T_NEKUDA = 35;
  public static final int T_BLADE_CONDITION_OPEN_TAG = 22;
  public static final int T_BLADE_SWITCH = 25;
  public static final int T_PHP_CONDITION_EXPRESSION = 30;
  public static final int T_BLADE_COMMENT = 4;
  public static final int T_BLADE_STOP = 11;
  public static final int EOF = 0;
  public static final int T_BLADE_OVERWRITE = 12;
  public static final int error = 1;
  public static final int T_BLADE_ENDIF = 24;
  public static final int T_BLADE_INLINE_PHP = 7;
  public static final int T_COMMA = 34;
  public static final int T_STRING = 32;
  public static final int T_VARIABLE = 33;
  public static final int T_BLADE_ENDSWITCH = 26;
  public static final int T_BLADE_PHP_ECHO = 29;
  public static final int T_BLADE_SHOW = 14;
  public static final int T_BLADE_INCLUDE = 8;
  public static final int T_BLADE_DIRECTIVE = 27;
  public static final int T_BLADE_CLOSE_ECHO = 6;
  public static final int T_BLADE_ENDFOREACH = 18;
  public static final int T_BLADE_FOREACH = 17;
  public static final int T_CLOSE_PARENTHESE = 37;
  public static final int T_INLINE_HTML = 2;
  public static final int T_BLADE_OPEN_ECHO = 5;
  public static final int T_OPEN_PARENTHESE = 36;
  public static final int T_PHP_LOOP_EXPRESSION = 28;
  public static final int T_BLADE_IF = 21;
  public static final int T_BLADE_YIELD = 16;
}

