# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: netbeans-nbm

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name : prepare the files from project
      run : mkdir -p  nb-plugin-package/src/main/java
      run : mkdir -p nb-plugin-package/src/main/nbm
      run : mkdir -p nb-plugin-package/src/main/resources/org/netbeans/modules/php/blade
      run : cp -rf ./src/org nb-plugin-package/src/main/java
      run : cp -rf ./src/org/netbeans/modules/php/blade/resources nb-plugin-package/src/main/resources/org/netbeans/modules/php/blade
      run : cp ./manifest.mf nb-plugin-package/src/main/nbm/manifest.mf
      run : cp ./.github/pom.xml nb-plugin-package/pom.xml
      run : cp ./nbproject/project.properties nb-plugin-package/project.properties
      run : cp ./LICENSE nb-plugin-package/LICENSE
      run : cd nb-plugin-package
      run : mvn package
